### ISSUE TITLE
Проблема со скачиваниями песен через VTL на Андроиде 

### ISSUE THREAD

**Issue by IGOR3K99** [vtosters/lite#10]
При скачивании песни VTL на Андроиде вылетает со следующей ошибкой:
java.lang.NoClassDefFoundError: Failed resolution of: Lru/vtosters/lite/downloaders/MusicDownloader;
	at com.vk.music.model.a.MusicTrackModelImpl.a(MusicTrackModelImpl.java:386)
	at com.vk.music.model.a.MusicTrackModelImpl.b(MusicTrackModelImpl.java:311)
	at com.vk.music.fragment.AudioPlayerFragment$c.onClick(AudioPlayerFragment.java:1079)
	at android.view.View.performClick(View.java:6617)
	at android.view.View.performClickInternal(View.java:6594)
	at android.view.View.access$3100(View.java:778)
	at android.view.View$PerformClick.run(View.java:25926)
	at android.os.Handler.handleCallback(Handler.java:873)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:193)
	at android.app.ActivityThread.main(ActivityThread.java:6672)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:495)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:860)
Caused by: java.lang.ClassNotFoundException: Didn't find class "ru.vtosters.lite.downloaders.MusicDownloader" on path: DexPathList[[zip file "/system/framework/android.test.mock.jar", zip file "/system/framework/org.apache.http.legacy.boot.jar", zip file "/system/framework/android.test.runner.jar", zip file "/mnt/expand/81c3ac1a-341b-4e1d-9e35-112bb68f2009/app/com.vtosters.lite-zpj8oQvwr3IUSlk1aegM5A==/base.apk"],nativeLibraryDirectories=[/mnt/expand/81c3ac1a-341b-4e1d-9e35-112bb68f2009/app/com.vtosters.lite-zpj8oQvwr3IUSlk1aegM5A==/lib/arm, /mnt/expand/81c3ac1a-341b-4e1d-9e35-112bb68f2009/app/com.vtosters.lite-zpj8oQvwr3IUSlk1aegM5A==/base.apk!/lib/armeabi-v7a, /system/lib]]
	at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:134)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
	... 14 more

Device{sdkVersion=28, productName='cereus', deviceName='cereus', boardName='cereus', cpuAbi='armeabi-v7a', manufacturerName='Xiaomi', brandName='xiaomi', modelName='Redmi 6'}
 VTL Version: 2.0 DEV, build: dd18b59

**Comment by rx1310** [comment]
Исправили же, чувак, в последнем коммите.
