### ISSUE TITLE
Ошибка репоста на свою страницу, вылет приложения

### ISSUE THREAD

**Issue by Ruslan-Rakshinsky** [vtosters/lite#1076]
При попытке репоста на свою страницу, всплывающее окно становится недоступным, и через некоторое время приложение вылетает

Как повторить:
1. Нажимаю на кнопку "репост" у любого поста
2. Выбираю "на своей странице"

Должен открываться интерфейс репоста на страницу, а вместо этого ничего не отображается. Также, то, что вызывает вылет приложения — список недавних контактов неактивен и, при попытке пролистать его, приложение вылетает. 

**Скриншот ошибки**
````
java.lang.IllegalStateException: Layout state should be one of 100 but it is 10
	at androidx.recyclerview.widget.RecyclerView$State.assertLayoutStep(RecyclerView.java:4)
	at androidx.recyclerview.widget.RecyclerView.dispatchLayoutStep3(RecyclerView.java:1)
	at androidx.recyclerview.widget.RecyclerView.dispatchLayout(RecyclerView.java:15)
	at androidx.recyclerview.widget.RecyclerView.consumePendingUpdateOperations(RecyclerView.java:21)
	at androidx.recyclerview.widget.RecyclerView$ViewFlinger.run(RecyclerView.java:4)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1231)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1239)
	at android.view.Choreographer.doCallbacks(Choreographer.java:899)
	at android.view.Choreographer.doFrame(Choreographer.java:827)
	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1214)
	at android.os.Handler.handleCallback(Handler.java:942)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:201)
	at android.os.Looper.loop(Looper.java:288)
	at android.app.ActivityThread.main(ActivityThread.java:7872)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:550)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:936)


Device information: commit='eba6c43', sdkVersion=33, productName='arrow_apollo', deviceName='apollo', boardName='kona', manufacturerName='Xiaomi', brandName='Xiaomi', modelName='M2007J3SY'
````

**Дополнительная информация о баге или мыслях почему оно может происходить (если есть)**
Как сам могу судить, приложение не может отрисовать необходимый layout. Смена Smallest Width в настройках устройства не помогает.

**Comment by Ruslan-Rakshinsky** [comment]
Ссылка на запись экрана
https://vimeo.com/793809075

**Comment by Ruslan-Rakshinsky** [comment]
Сброс настроек и даже очистка данных приложения проблему не решили.

**Comment by Ruslan-Rakshinsky** [comment]
Проверил, проблема проявляется на разных прошивках (ArrowOS, LineageOS, FlamingoOS, Xiaomi.eu)

**Comment by Ruslan-Rakshinsky** [comment]
Выяснил, что вызывало такое поведение. В списке недавних чатов была переписка с контактом из телефонной книжки. То есть, диалог без учётной записи мешал отрисовке активити репоста.
