### ISSUE TITLE
Вылет приложения при попытке смены языка

### ISSUE THREAD

**Issue by trefacode** [vtosters/lite#1182]
**Опишите сам баг**
Пытаюсь переключить язык в приложении

**Опишите действия для воспроизведения ошибки**
1. Открыл настройки
2. Тыкнул по кнопке смены языка

java.lang.RuntimeException: Unable to start activity ComponentInfo{com.android.settings/com.android.settings.localepicker.AppLocalePickerActivity}: java.lang.NullPointerException: Attempt to invoke virtual method 'void android.app.ActionBar.setDisplayHomeAsUpEnabled(boolean)' on a null object reference
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3805)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3951)
	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:101)
	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2405)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loopOnce(Looper.java:211)
	at android.os.Looper.loop(Looper.java:300)
	at android.app.ActivityThread.main(ActivityThread.java:8152)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:580)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1028)
Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'void android.app.ActionBar.setDisplayHomeAsUpEnabled(boolean)' on a null object reference
	at com.android.settings.localepicker.AppLocalePickerActivity.onCreate(AppLocalePickerActivity.java:75)
	at android.app.Activity.performCreate(Activity.java:8508)
	at android.app.Activity.performCreate(Activity.java:8472)
	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1417)
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3786)
	... 12 more

**Информация об устройстве:** 

- Commit: cd08354
- Android SDK: 33
- Product: amber_global
- Device: amber
- Board: amber
- Manufacturer: Xiaomi
- Brand: Xiaomi
- Model: 21081111RG
- Miui Version Code: 14
- Miui Version Name: V140
- Miui Version Incremental Code: V14.0.4.0.TKWMIXM

**Comment by gdlbo** [comment]
miui не поддерживает эту функцию
https://xiaomi.eu/community/threads/miui-14-per-app-language-support.69022/
