### ISSUE TITLE
Ошибка кеширования треков 

### ISSUE THREAD

**Issue by VwV-Joining-VwV** [vtosters/lite#1195]
1. Кешировал 1.5k треков
2. На 100+ появилась ошибка
______________________________________________________

java8.util.concurrent.CompletionException: java.lang.RuntimeException: java.net.SocketException: Software caused connection abort
	at java8.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:305)
	at java8.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:312)
	at java8.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1804)
	at java8.util.concurrent.CompletableFuture$AsyncRun.exec(CompletableFuture.java:1793)
	at java8.util.concurrent.FJTask.doExec(FJTask.java:271)
	at java8.util.concurrent.FJPool.runWorker(FJPool.java:1495)
	at java8.util.concurrent.FJWorkerThread.run(FJWorkerThread.java:122)
Caused by: java.lang.RuntimeException: java.net.SocketException: Software caused connection abort
	at ru.vtosters.lite.music.M3UDownloader.lambda$parse$0(M3UDownloader.java:93)
	at ru.vtosters.lite.music.M3UDownloader$$ExternalSyntheticLambda0.run(Unknown Source:14)
	at java8.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1801)
	... 4 more
Caused by: java.net.SocketException: Software caused connection abort
	at java.net.SocketInputStream.socketRead0(Native Method)
	at java.net.SocketInputStream.socketRead(SocketInputStream.java:118)
	at java.net.SocketInputStream.read(SocketInputStream.java:173)
	at java.net.SocketInputStream.read(SocketInputStream.java:143)
	at com.android.org.conscrypt.ConscryptEngineSocket$SSLInputStream.readFromSocket(ConscryptEngineSocket.java:945)
	at com.android.org.conscrypt.ConscryptEngineSocket$SSLInputStream.processDataFromSocket(ConscryptEngineSocket.java:909)
	at com.android.org.conscrypt.ConscryptEngineSocket$SSLInputStream.readUntilDataAvailable(ConscryptEngineSocket.java:824)
	at com.android.org.conscrypt.ConscryptEngineSocket$SSLInputStream.read(ConscryptEngineSocket.java:797)
	at com.android.okhttp.okio.Okio$2.read(Okio.java:138)
	at com.android.okhttp.okio.AsyncTimeout$2.read(AsyncTimeout.java:213)
	at com.android.okhttp.okio.RealBufferedSource.indexOf(RealBufferedSource.java:307)
	at com.android.okhttp.okio.RealBufferedSource.indexOf(RealBufferedSource.java:301)
	at com.android.okhttp.okio.RealBufferedSource.readUtf8LineStrict(RealBufferedSource.java:197)
	at com.android.okhttp.internal.http.Http1xStream.readResponse(Http1xStream.java:188)
	at com.android.okhttp.internal.http.Http1xStream.readResponseHeaders(Http1xStream.java:129)
	at com.android.okhttp.internal.http.HttpEngine.readNetworkResponse(HttpEngine.java:750)
	at com.android.okhttp.internal.http.HttpEngine.readResponse(HttpEngine.java:622)
	at com.android.okhttp.internal.huc.HttpURLConnectionImpl.execute(HttpURLConnectionImpl.java:475)
	at com.android.okhttp.internal.huc.HttpURLConnectionImpl.getResponse(HttpURLConnectionImpl.java:411)
	at com.android.okhttp.internal.huc.HttpURLConnectionImpl.getInputStream(HttpURLConnectionImpl.java:248)
	at com.android.okhttp.internal.huc.DelegatingHttpsURLConnection.getInputStream(DelegatingHttpsURLConnection.java:211)
	at com.android.okhttp.internal.huc.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:30)
	at ru.vtosters.lite.utils.IOUtils.openStream(IOUtils.java:43)
	at ru.vtosters.lite.music.M3UDownloader.lambda$parse$0(M3UDownloader.java:82)
	... 6 more

Device information: commit='21fc171', isMilkshake='true', sdkVersion='31', productName='lemon_ru', deviceName='lemon', boardName='lemon', manufacturerName='Xiaomi', brandName='Redmi', MiuiUiVersionCode='13', MiuiUiVersionName='V130', MiuiUiVersionIncrementalCode='V13.0.1.0.SJQRUXM', modelName='M2010J19SY'

**Comment by ayonovdenizs** [comment]
invalid
