### ISSUE TITLE
Ошибка загрузки (скачивания) музыки 

### ISSUE THREAD

**Issue by SneppiRus** [vtosters/lite#1228]
**Опишите сам баг**
При попытке загрузить музыку в кеш или мп3, приложение вылетает и выдает ошибку

**Опишите действия для воспроизведения ошибки.**
Зашёл в свою музыку, нажал на значок установки.
**Опишите ожидаемый результат**
Музыка должна была загрузиться в кеш.

**Скриншот ошибки**
https://ibb.co/HGj8TR2

**Скопируйте сюда информацию об устройстве нажав на кнопку "Скопировать информацию об устройстве" в Настройках -> Redmi note 8 pro**

**Дополнительная информация о баге или мыслях почему оно может происходить (если есть)**
не понимаю

**Comment by meph1les** [comment]
![Screenshot_2023-04-28-11-45-32-756_com mi android globallauncher](https://user-images.githubusercontent.com/132054248/235102536-33f0c821-e633-4c2a-abdf-be37ad7eb455.jpg)
буквально несколько дней назад все нормально скачивалось, но буквально со вчера (где-то вечером) скачивать музыку втлайт напрочь отказывался

**Comment by GooDoG337** [comment]
@meph1les Не по шаблону

**Comment by KirikoKazuno** [comment]
**Информация об устройстве:** 

- Commit: 681dd17
- Android SDK: 33
- Product: lisa_ru
- Device: lisa
- Board: lisa
- Manufacturer: Xiaomi
- Brand: Xiaomi
- Model: 2109119DG
- Miui Version Code: 14
- Miui Version Name: V140
- Miui Version Incremental Code: V14.0.3.0.TKORUXM
P.S Таже ошибка, но скачивается от 19-25≈ не более

**Comment by danyyok** [comment]
> - Commit: 681dd17
> P.S Таже ошибка, но скачивается от 19-25≈ не более

Скиньте полный лог файлом в втостерс чат, посмотрим.

**Comment by KirikoKazuno** [comment]
java8.util.concurrent.CompletionException: java.lang.RuntimeException: java.io.FileNotFoundException: https://sgi2.ufanet.vkuseraudio.net/s/v1/ac/1Y2-48Ei_Sc63BkOpiUvytQwo2eJwaXf8DimtXmyLdt-26ESdG3rVHttugn7Agt33PV4qhn5-zomGeq7tpianHUbwda0HzjXOqfP0CSl5DGBHaxptuj4SBeug2y5LUAyJq3rTSF1KT-BfYLG9H4WHUX2rBGQAyVQe9G7MnqpoM8Cxgg/seg-1-a1.ts
	at java8.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:305)
	at java8.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:312)
	at java8.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1804)
	at java8.util.concurrent.CompletableFuture$AsyncRun.exec(CompletableFuture.java:1793)
	at java8.util.concurrent.FJTask.doExec(FJTask.java:271)
	at java8.util.concurrent.FJPool.runWorker(FJPool.java:1495)
	at java8.util.concurrent.FJWorkerThread.run(FJWorkerThread.java:122)
Caused by: java.lang.RuntimeException: java.io.FileNotFoundException: https://sgi2.ufanet.vkuseraudio.net/s/v1/ac/1Y2-48Ei_Sc63BkOpiUvytQwo2eJwaXf8DimtXmyLdt-26ESdG3rVHttugn7Agt33PV4qhn5-zomGeq7tpianHUbwda0HzjXOqfP0CSl5DGBHaxptuj4SBeug2y5LUAyJq3rTSF1KT-BfYLG9H4WHUX2rBGQAyVQe9G7MnqpoM8Cxgg/seg-1-a1.ts
	at ru.vtosters.lite.music.M3UDownloader.processTransportStream(M3UDownloader.java:134)
	at ru.vtosters.lite.music.M3UDownloader.lambda$createFutures$6$ru-vtosters-lite-music-M3UDownloader(M3UDownloader.java:110)
	at ru.vtosters.lite.music.M3UDownloader$$ExternalSyntheticLambda6.run(Unknown Source:16)
	at java8.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1801)
	... 4 more
Caused by: java.io.FileNotFoundException: https://sgi2.ufanet.vkuseraudio.net/s/v1/ac/1Y2-48Ei_Sc63BkOpiUvytQwo2eJwaXf8DimtXmyLdt-26ESdG3rVHttugn7Agt33PV4qhn5-zomGeq7tpianHUbwda0HzjXOqfP0CSl5DGBHaxptuj4SBeug2y5LUAyJq3rTSF1KT-BfYLG9H4WHUX2rBGQAyVQe9G7MnqpoM8Cxgg/seg-1-a1.ts
	at com.android.okhttp.internal.huc.HttpURLConnectionImpl.getInputStream(HttpURLConnectionImpl.java:255)
	at com.android.okhttp.internal.huc.DelegatingHttpsURLConnection.getInputStream(DelegatingHttpsURLConnection.java:211)
	at com.android.okhttp.internal.huc.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:30)
	at ru.vtosters.lite.utils.IOUtils.openStream(IOUtils.java:41)
	at ru.vtosters.lite.music.M3UDownloader.processTransportStream(M3UDownloader.java:117)
	... 7 more


Device information: commit='681dd17', isMilkshake='true', sdkVersion='33', productName='lisa_ru', deviceName='lisa', boardName='lisa', manufacturerName='Xiaomi', brandName='Xiaomi', MiuiUiVersionCode='14', MiuiUiVersionName='V140', MiuiUiVersionIncrementalCode='V14.0.3.0.TKORUXM', modelName='2109119DG'
