### ISSUE TITLE
Ошибка кэширования музыки 

### ISSUE THREAD

**Issue by Volt567** [vtosters/lite#1269]
**Опишите сам баг**
Если нажать  добавить в кеш, то приложение вылетает , и поевляется такое уведомление (далее на скриншоте) 

**Скриншот ошибки**
![IMG_20230506_173907.jpg](https://user-images.githubusercontent.com/114720843/236619682-ce0e8599-1fbe-40d0-b162-e5e70fad20c1.jpg)

**Логи**

java.lang.NullPointerException: Attempt to invoke virtual method 'int java.lang.String.length()' on a null object reference
	at java.net.URLEncoder.encode(URLEncoder.java:204)
	at ru.vtosters.lite.music.M3UDownloader.parse(M3UDownloader.java:88)
	at ru.vtosters.lite.music.M3UDownloader.downloadTrack(M3UDownloader.java:59)
	at ru.vtosters.lite.music.downloader.TrackDownloader.lambda$download$0(TrackDownloader.java:50)
	at ru.vtosters.lite.music.downloader.TrackDownloader$$ExternalSyntheticLambda0.run(Unknown Source:10)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
	at java.lang.Thread.run(Thread.java:920)

Device information: commit='cc55d5d', isMilkshake='true', sdkVersion='31', productName='sweet_ru', deviceName='sweet', boardName='sweet', manufacturerName='Xiaomi', brandName='Redmi', MiuiUiVersionCode='13', MiuiUiVersionName='V130', MiuiUiVersionIncrementalCode='V13.0.10.0.SKFRUXM', modelName='M2101K6G'

**Информация об устройстве:** 

- Commit: cc55d5d
- Android SDK: 31
- Product: sweet_ru
- Device: sweet
- Board: sweet
- Manufacturer: Xiaomi
- Brand: Redmi
- Model: M2101K6G
- Miui Version Code: 13
- Miui Version Name: V130
- Miui Version Incremental Code: V13.0.10.0.SKFRUXM

**Дополнительная информация о баге или мыслях почему оно может происходить (если есть)**

**Comment by danyyok** [comment]
@Volt567 https://t.me/vtosters_faq/110

Duplicate+invalid issue 
#1129

попробуйте фикс
https://t.me/vtosterschat/3467846/3498181
Если также не будет скачиваться - скидывайте логи в обсуждение Beta/Unstable

**Comment by Volt567** [comment]
> @Volt567 https://t.me/vtosters_faq/110
> 
> Duplicate+invalid issue 
> #1129
> 
> попробуйте фикс
> https://t.me/vtosterschat/3467846/3498181
> Если также не будет скачиваться - скидывайте логи в обсуждение Beta/Unstable

Теперь заработало
