### ISSUE TITLE
Ошибка при попытке смены языка приложения в настройках VTLite

### ISSUE THREAD

**Issue by therteenten** [vtosters/lite#1277]
**Опишите сам баг**
Случайно наткнулся на вылет в версии 0.6.3, когда нажал на пункт "Язык приложения" в настройках:

![Screenshot_2023-05-08-09-00-39-135_com.vtosters.lite-edit.jpg](https://user-images.githubusercontent.com/124383082/236745819-a3f848eb-beee-4be0-92eb-92b4a0fb0ce0.jpg)

**Опишите действия для воспроизведения ошибки**
1. Открыт клиент
2. Открыл настройки клиента
3. Пролистал до пункта "Язык приложения"
4. Нажал на пункт
5. Вылет

**Опишите ожидаемый результат**
Да ниче не ожидал. Случайно нажал.

**Скриншот ошибки**
![Screenshot_2023-05-08-09-07-34-107_com.miui.bugreport.jpg](https://user-images.githubusercontent.com/124383082/236746847-0a5ccec4-7ee5-47c2-b8f9-7ee0599f8d80.jpg)

```
java.lang.RuntimeException: Unable to start activity ComponentInfo{com.android.settings/com.android.settings.localepicker.AppLocalePickerActivity}: java.lang.NullPointerException: Attempt to invoke virtual method 'void android.app.ActionBar.setDisplayHomeAsUpEnabled(boolean)' on a null object reference
	at android.app.ActivityThread.performLaunchActivity(Unknown Source:902)
	at android.app.ActivityThread.handleLaunchActivity(Unknown Source:77)
	at android.app.servertransaction.LaunchActivityItem.execute(Unknown Source:79)
	at android.app.servertransaction.TransactionExecutor.executeCallbacks(Unknown Source:77)
	at android.app.servertransaction.TransactionExecutor.execute(Unknown Source:76)
	at android.app.ActivityThread$H.handleMessage(Unknown Source:172)
	at android.os.Handler.dispatchMessage(Unknown Source:19)
	at android.os.Looper.loopOnce(Unknown Source:182)
	at android.os.Looper.loop(Unknown Source:82)
	at android.app.ActivityThread.main(Unknown Source:123)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(Unknown Source:11)
	at com.android.internal.os.ZygoteInit.main(Unknown Source:312)
Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'void android.app.ActionBar.setDisplayHomeAsUpEnabled(boolean)' on a null object reference
	at com.android.settings.localepicker.AppLocalePickerActivity.onCreate(Unknown Source:94)
	at android.app.Activity.performCreate(Unknown Source:127)
	at android.app.Activity.performCreate(Unknown Source:1)
	at android.app.Instrumentation.callActivityOnCreate(Unknown Source:3)
	at android.app.ActivityThread.performLaunchActivity(Unknown Source:627)
	... 12 more

```

**Информация об устройстве:** 

- Commit: 681dd17
- Android SDK: 33
- Product: vayu_global
- Device: vayu
- Board: vayu
- Manufacturer: Xiaomi
- Brand: POCO
- Model: M2102J20SG
- Miui Version Code: 14
- Miui Version Name: V140
- Miui Version Incremental Code: V14.0.1.0.TJUMIXM

**Comment by danyyok** [comment]
Миюай криво сделали (а че еще) переключение языка в приложениях
Вообще, эта настройка должна пропадать если у тебя миюай

**Comment by therteenten** [comment]
> Миюай криво сделали (а че еще) переключение языка в приложениях
> Вообще, эта настройка должна пропадать если у тебя миюай

Так-то я ею и не пользуюсь. Просто обнаружил, решил поделиться.

**Comment by gdlbo** [comment]
Крашнулись настройки Miui, не VTLite
