### ISSUE TITLE
Layout новостной ленты перестал работать

### ISSUE THREAD

**Issue by UrShade** [vtosters/lite#1291]
При загрузке приложения с рабочего стола, происходит подобное. Если прогрузиться из уведомления с сообщения, то вроде как лента работает. Содержимое лог файла и скриншот ниже
```
java.lang.IllegalStateException: Layout state should be one of 100 but it is 10
	at androidx.recyclerview.widget.RecyclerView$State.assertLayoutStep(RecyclerView.java:4)
	at androidx.recyclerview.widget.RecyclerView.dispatchLayoutStep3(RecyclerView.java:1)
	at androidx.recyclerview.widget.RecyclerView.dispatchLayout(RecyclerView.java:15)
	at androidx.recyclerview.widget.RecyclerView.consumePendingUpdateOperations(RecyclerView.java:21)
	at androidx.recyclerview.widget.RecyclerView$ViewFlinger.run(RecyclerView.java:4)
	at android.view.Choreographer$CallbackRecord.run(Unknown Source:20)
	at android.view.Choreographer.doCallbacks(Unknown Source:84)
	at android.view.Choreographer.doFrame(Unknown Source:324)
	at android.view.Choreographer$FrameDisplayEventReceiver.run(Unknown Source:11)
	at android.os.Handler.handleCallback(Unknown Source:2)
	at android.os.Handler.dispatchMessage(Unknown Source:4)
	at android.os.Looper.loopOnce(Unknown Source:176)
	at android.os.Looper.loop(Unknown Source:76)
	at android.app.ActivityThread.main(Unknown Source:155)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(Unknown Source:11)
	at com.android.internal.os.ZygoteInit.main(Unknown Source:309)


Device information: commit='681dd17', isMilkshake='true', sdkVersion='31', productName='surya_global', deviceName='surya', boardName='surya', manufacturerName='Xiaomi', brandName='POCO', MiuiUiVersionCode='14', MiuiUiVersionName='V140', MiuiUiVersionIncrementalCode='V14.0.1.0.SJGMIXM', modelName='M2007J20CG'
``` 

![Screenshot_2023-05-12-09-46-25-010_com vtosters lite](https://github.com/vtosters/lite/assets/47716746/e56ace48-f32a-45ff-9f2c-4ee6eb6f8ad3)

**Comment by UrShade** [comment]
Возможно, это был баг ВК. Проблема пока что проблема перестала возникать

**Comment by UrShade** [comment]
Проблема ушла сама собой. Предполагаю, это был баг серверов
