### ISSUE TITLE
Краш при запуске

### ISSUE THREAD

**Issue by max22062019** [vtosters/lite#135]
`
<<< log_count = 69 >>>
[04-12 08:04:40.897 3080:3416 I/ApplicationPolicy]
isApplicationExternalStorageWhitelisted:com.vtosters.lite user:0

[04-12 08:04:40.897 3080:3416 D/ActivityManager]
package  com.vtosters.lite, user - 0 is SDcard whitelisted

[04-12 08:04:40.897 3080:3416 I/ApplicationPolicy]
isApplicationExternalStorageBlacklisted:com.vtosters.lite user:0

[04-12 08:04:40.898 3080:3416 I/ApplicationPolicy]
isApplicationExternalStorageBlacklisted:com.vtosters.lite user:0

[04-12 08:04:40.931 3080:3210 I/ActivityManager]
Start proc 5111:com.vtosters.lite/u0a286 for activelaunch {com.vtosters.lite/com.vtosters.lite.VTIconDefault}

[04-12 08:04:40.969 3080:3145 I/ActivityTaskManager]
START u0 {act=android.intent.action.MAIN cat=[android.intent.category.LAUNCHER] flg=0x10200000 cmp=com.vtosters.lite/.VTIconDefault bnds=[513,614][666,808]} from uid 10116

[04-12 08:04:40.985 2765:2886 I/SurfaceFlinger]
createSurf start. lock debugging [AppWindowToken{f52ee64 token=Token{7497ff7 ActivityRecord{6ddff6 u0 com.vtosters.lite/.VTIconDefault t85}}}]

[04-12 08:04:40.986 2765:2886 I/SurfaceFlinger]
id=688 createSurf (0x0),-1 flag=80004, AppWindowToken{f52ee64 token=Token{7497ff7 ActivityRecord{6ddff6 u0 com.vtosters.lite/.VTIconDefault t85}}}#0

[04-12 08:04:40.993 3080:3203 D/GameManagerService]
MultiWindowEventListener.onFocusedStackChanged(), state=0, top=ComponentInfo{com.vtosters.lite/com.vtosters.lite.VTIconDefault}

[04-12 08:04:40.993 3080:3203 D/GameManagerService]
MultiWindowEventListener.onFocusedStackChanged(), pkgName: com.vtosters.lite, clsName: com.vtosters.lite.VTIconDefault, FgActivityName:com.vtosters.lite/.VTIconDefault, userID:0

[04-12 08:04:40.993 3080:3413 D/GameManagerService]
onLooperPrepared(), msg: { when=0 what=10000 obj=ComponentInfo{com.vtosters.lite/com.vtosters.lite.VTIconDefault} target=com.samsung.android.game.GameManagerService$FgCheckThread$1 }

[04-12 08:04:40.993 3080:3413 D/GameManagerService]
notifyResumePause(). pkg: com.vtosters.lite, type: 4, isMinimized: false, isTunableApp: false

[04-12 08:04:40.994 3080:3203 D/GameSDKService]
MultiWindowEventListener.onFocusStackChanged(), state=0, top=ComponentInfo{com.vtosters.lite/com.vtosters.lite.VTIconDefault}

[04-12 08:04:40.996 3080:5017 I/ActivityManager]
DSS OFF for com.vtosters.lite

[04-12 08:04:41.013 3080:3204 D/PhoneWindow]
forceLight changed to true [Splash Screen com.vtosters.lite] from com.android.internal.policy.PhoneWindow.updateForceLightNavigationBar:4238 com.android.internal.policy.DecorView.updateColorViews:1510 com.android.internal.policy.PhoneWindow.dispatchWindowAttributesChanged:3216 android.view.Window.setFlags:1148 com.android.internal.policy.PhoneWindow.generateLayout:2444 

[04-12 08:04:41.013 3080:3204 D/PhoneWindow]
forceLight changed to false [Splash Screen com.vtosters.lite] from com.android.internal.policy.PhoneWindow.updateForceLightNavigationBar:4244 com.android.internal.policy.DecorView.updateColorViews:1510 com.android.internal.policy.PhoneWindow.dispatchWindowAttributesChanged:3216 android.view.Window.setFlags:1148 com.android.internal.policy.PhoneWindow.generateLayout:2590 

[04-12 08:04:41.017 3080:3413 D/GameManagerService]
onLooperPrepared(), msg: { when=0 what=10010 obj=com.vtosters.lite target=com.samsung.android.game.GameManagerService$FgCheckThread$1 }

[04-12 08:04:41.017 3080:3413 D/GameManagerService]
handleMessage(), MSG_APP_CREATE. pkgName: com.vtosters.lite

[04-12 08:04:41.017 3080:5017 D/GamePkgDataHelper]
notifyAppCreate(), pkgName: com.vtosters.lite, sendRet: true

[04-12 08:04:41.021 3080:5017 D/MARsPolicyManager]
onPackageResumedFG pkgName = com.vtosters.lite, userId = 0

[04-12 08:04:41.024 2765:2886 I/SurfaceFlinger]
createSurf start. lock debugging [22c32a6 Splash Screen com.vtosters.lite]

[04-12 08:04:41.024 2765:2886 I/SurfaceFlinger]
id=689 createSurf (0x0),-1 flag=80004, 22c32a6 Splash Screen com.vtosters.lite#0

[04-12 08:04:41.025 3080:3203 D/GameSDKService]
MultiWindowEventListener.onFocusStackChanged(): com.vtosters.lite

[04-12 08:04:41.029 3080:3204 V/WindowManager]
Relayout Window{22c32a6 u0 Splash Screen com.vtosters.lite}: viewVisibility=0 req=720x1280

[04-12 08:04:41.031 2765:2886 I/SurfaceFlinger]
createSurf start. lock debugging [Splash Screen com.vtosters.lite]

[04-12 08:04:41.032 2765:2886 I/SurfaceFlinger]
id=690 createSurf (720x1280),1 flag=404, Splash Screen com.vtosters.lite#0

[04-12 08:04:41.032 3080:3204 D/WindowManager]
makeSurface duration=1 name=Splash Screen com.vtosters.lite

[04-12 08:04:41.036 3080:3201 D/CodecSolution]
isMaxAspectPackageEx: com.vtosters.lite : false(0)

[04-12 08:04:41.043 3080:3204 D/WindowManager]
finishDrawingWindow: Window{22c32a6 u0 Splash Screen com.vtosters.lite} mDrawState=DRAW_PENDING

[04-12 08:04:41.050 3080:3204 V/WindowManager]
performShow on Window{22c32a6 u0 Splash Screen com.vtosters.lite}: mDrawState=READY_TO_SHOW readyForDisplay=false starting=true during animation: policyVis=true parentHidden=false tok.hiddenRequested=false tok.hidden=true animating=true tok animating=true Callers=com.android.server.wm.WindowState.performShowLocked:4660 com.android.server.wm.WindowStateAnimator.commitFinishDrawingLocked:380 com.android.server.wm.DisplayContent.lambda$new$8$DisplayContent:935 com.android.server.wm.-$$Lambda$DisplayContent$qxt4izS31fb0LF2uo_OF9DMa7gc.accept:4 

[04-12 08:04:41.053 3080:3204 I/WindowManager]
Reparenting to leash, surface=Surface(name=AppWindowToken{f52ee64 token=Token{7497ff7 ActivityRecord{6ddff6 u0 com.vtosters.lite/.VTIconDefault t85}}})/@0xc58d332

[04-12 08:04:41.053 2765:2886 I/SurfaceFlinger]
createSurf start. lock debugging [Surface(name=AppWindowToken{f52ee64 token=Token{7497ff7 ActivityRecord{6ddff6 u0 com.vtosters.lite/.VTIconDefault t85}}})/@0xc58d332 - animation-leash]

[04-12 08:04:41.054 2765:2886 I/SurfaceFlinger]
id=692 createSurf (0x0),-1 flag=80004, Surface(name=AppWindowToken{f52ee64 token=Token{7497ff7 ActivityRecord{6ddff6 u0 com.vtosters.lite/.VTIconDefault t85}}})/@0xc58d332 - animation-leash#0

[04-12 08:04:41.054 3080:3204 D/WindowManager]
makeSurface duration=1 leash=Surface(name=Surface(name=AppWindowToken{f52ee64 token=Token{7497ff7 ActivityRecord{6ddff6 u0 com.vtosters.lite/.VTIconDefault t85}}})/@0xc58d332 - animation-leash)/@0xcd75883

[04-12 08:04:41.059 3080:3201 D/WindowManager]
setSystemUiVisibility: displayId=0, vis=0xa008, fullVis=0x2000, dockVis=0x0, win=Window{22c32a6 u0 Splash Screen com.vtosters.lite}

[04-12 08:04:41.078 3080:3203 D/GamePkgDataHelper]
getSosPolicy(). com.vtosters.lite

[04-12 08:04:41.078 3080:3203 D/GameManagerService]
identifyGamePackage. com.vtosters.lite, mCurrentUserId: 0, callerUserId: 0

[04-12 08:04:41.079 3080:3203 D/GamePkgDataHelper]
getGamePkgData(). com.vtosters.lite

[04-12 08:04:41.079 3080:3203 D/GameManagerService]
noteResumeComponent(), resumeComponent: com.vtosters.lite

[04-12 08:04:41.079 3080:3413 D/GameManagerService]
onLooperPrepared(), msg: { when=0 what=10000 obj=ComponentInfo{com.vtosters.lite/com.vtosters.lite.MainActivity} target=com.samsung.android.game.GameManagerService$FgCheckThread$1 }

[04-12 08:04:41.079 3080:3413 D/GameManagerService]
notifyResumePause(). pkg: com.vtosters.lite, type: 4, isMinimized: false, isTunableApp: false

[04-12 08:04:41.080 3080:5017 D/GamePkgDataHelper]
getSosPolicy(). com.vtosters.lite

[04-12 08:04:41.097 2765:2765 I/SurfaceFlinger]
Display 0 HWC layers:
    type    |    handle    | flag |  format   |   source crop (l,t,r,b)    |         frame       | name 
------------+--------------+------+-----------+----------------------------+---------------------+------
     CLIENT | 0xeee38b40 | 0002 | RGBA_8888 |   0.0  116.0  590.0 1164.0 |    0    0  720 1280 | com.android.systemui.ImageWallpaper$_3451#0
     CLIENT | 0xeee39900 | 0000 | RGBA_8888 |   0.0    0.0  720.0 1280.0 |    0    0  720 1280 | com.sec.android.app.launcher/com.sec[...].activities.LauncherActivity$_3738#0
     CLIENT | 0xeee39f40 | 0002 | RGBA_8888 |   0.0    0.0  720.0 1280.0 |    0    0  720 1280 | Splash Screen com.vtosters.lite#0
     DEVICE | 0xef3eaa40 | 0000 | RGBA_8888 |   0.0    0.0  720.0   42.0 |    0    0  720   42 | StatusBar$_3451#0

[04-12 08:04:41.174 3080:3482 D/MdnieScenarioControlService]
 packageName : com.vtosters.lite    className : com.vtosters.lite.MainActivity

[04-12 08:04:41.206 3080:3653 I/WindowManager]
Reparenting to original parent: Surface(name=Task=85)/@0x13c9156, destroyLeash=true, surface=Surface(name=AppWindowToken{f52ee64 token=Token{7497ff7 ActivityRecord{6ddff6 u0 com.vtosters.lite/.VTIconDefault t85}}})/@0xc58d332

[04-12 08:04:41.211 2765:3022 I/Layer]
id=692 removeFromCurrentState Surface(name=AppWindowToken{f52ee64 token=Token{7497ff7 ActivityRecord{6ddff6 u0 com.vtosters.lite/.VTIconDefault t85}}})/@0xc58d332 - animation-leash#0 (51)

[04-12 08:04:41.233 2765:2765 E/Layer]
[Surface(name=AppWindowToken{f52ee64 token=Token{7497ff7 ActivityRecord{6ddff6 u0 com.vtosters.lite/.VTIconDefault t85}}})/@0xc58d332 - animation-leash#0] No local sync point found, barrierLayer : [com.sec.android.app.launcher/com.sec.android.app.launcher.activities.LauncherActivity$_3738#0]

[04-12 08:04:41.233 2765:2765 E/Layer]
[Surface(name=AppWindowToken{f52ee64 token=Token{7497ff7 ActivityRecord{6ddff6 u0 com.vtosters.lite/.VTIconDefault t85}}})/@0xc58d332 - animation-leash#0] No local sync point found, barrierLayer : [com.sec.android.app.launcher/com.sec.android.app.launcher.activities.LauncherActivity$_3738#0]

[04-12 08:04:41.238 2765:2765 I/SurfaceFlinger]
Display 0 HWC layers:
    type    |    handle    | flag |  format   |   source crop (l,t,r,b)    |         frame       | name 
------------+--------------+------+-----------+----------------------------+---------------------+------
     DEVICE | 0xeee39f40 | 0002 | RGBA_8888 |   0.0    0.0  720.0 1280.0 |    0    0  720 1280 | Splash Screen com.vtosters.lite#0
     DEVICE | 0xef3eaa40 | 0000 | RGBA_8888 |   0.0    0.0  720.0   42.0 |    0    0  720   42 | StatusBar$_3451#0

[04-12 08:04:41.242 5111:5150 E/AndroidRuntime]
FATAL EXCEPTION: AsyncTask #1
Process: com.vtosters.lite, PID: 5111
java.lang.SecurityException: Not allowed to bind to service Intent { act=com.google.android.gms.ads.identifier.service.START pkg=com.google.android.gms }
	at android.app.ContextImpl.bindServiceCommon(ContextImpl.java:1811)
	at android.app.ContextImpl.bindService(ContextImpl.java:1721)
	at android.content.ContextWrapper.bindService(ContextWrapper.java:719)
	at com.facebook.internal.AttributionIdentifiers.d(AttributionIdentifiers.java:150)
	at com.facebook.internal.AttributionIdentifiers.b(AttributionIdentifiers.java:78)
	at com.facebook.internal.AttributionIdentifiers.a(AttributionIdentifiers.java:180)
	at com.facebook.internal.FetchedAppSettingsManager.c(FetchedAppSettingsManager.java:371)
	at com.facebook.internal.FetchedAppSettingsManager.b(FetchedAppSettingsManager.java:62)
	at com.facebook.internal.FetchedAppSettingsManager$1.run(FetchedAppSettingsManager.java:179)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
	at java.lang.Thread.run(Thread.java:919)

[04-12 08:04:41.260 3080:5017 W/ActivityManager]
crash : com.vtosters.lite,0

[04-12 08:04:41.265 3080:5017 W/ActivityTaskManager]
  Force finishing activity com.vtosters.lite/.VTIconDefault

[04-12 08:04:41.271 2765:3022 I/SurfaceFlinger]
id=692 Removed Surface(name=AppWindowToken{f52ee64 token=Token{7497ff7 ActivityRecord{6ddff6 u0 com.vtosters.lite/.VTIconDefault t85}}})/@0xc58d332 - animation-leash#0 (51)

[04-12 08:04:41.289 2765:2765 I/Layer]
id=692[1] Destroyed Surface(name=AppWindowToken{f52ee64 token=Token{7497ff7 ActivityRecord{6ddff6 u0 com.vtosters.lite/.VTIconDefault t85}}})/@0xc58d332 - animation-leash#0

[04-12 08:04:41.305 31973:5169 D/AppErrorNotification]
errorType : 24, process : com.vtosters.lite , uid : 0

[04-12 08:04:41.351 31973:5169 W/AppErrorNotification]
Skip. com.vtosters.liteis excluded

[04-12 08:04:41.370 3080:5022 I/ActivityManager]
Process com.vtosters.lite (pid 5111) has died: vis+99 TOP (511,1003)

[04-12 08:04:41.376 3080:5022 E/WindowManager]
win=Window{22c32a6 u0 Splash Screen com.vtosters.lite EXITING} destroySurfaces: appStopped=false win.mWindowRemovalAllowed=true win.mRemoveOnExit=true win.mViewVisibility=0 caller=com.android.server.wm.AppWindowToken.destroySurfaces:1200 com.android.server.wm.AppWindowToken.destroySurfaces:1181 com.android.server.wm.WindowState.onExitAnimationDone:5030 com.android.server.wm.-$$Lambda$01bPtngJg5AqEoOWfW3rWfV7MH4.accept:2 java.util.ArrayList.forEach:1262 com.android.server.wm.AppWindowToken.onAnimationFinished:3549 com.android.server.wm.AppWindowToken.commitVisibility:860 

[04-12 08:04:41.376 3080:5022 I/WindowManager]
Destroying surface Surface(name=Splash Screen com.vtosters.lite)/@0xc92fa51 called by com.android.server.wm.WindowStateAnimator.destroySurface:1734 com.android.server.wm.WindowStateAnimator.destroySurfaceLocked:693 com.android.server.wm.WindowState.destroySurfaceUnchecked:3482 com.android.server.wm.WindowState.destroySurface:3456 com.android.server.wm.AppWindowToken.destroySurfaces:1200 com.android.server.wm.AppWindowToken.destroySurfaces:1181 com.android.server.wm.WindowState.onExitAnimationDone:5030 com.android.server.wm.-$$Lambda$01bPtngJg5AqEoOWfW3rWfV7MH4.accept:2 

[04-12 08:04:41.377 2765:3022 I/Layer]
id=690 removeFromCurrentState Splash Screen com.vtosters.lite#0 (48)

[04-12 08:04:41.380 2765:3022 I/Layer]
id=689 removeFromCurrentState 22c32a6 Splash Screen com.vtosters.lite#0 (48)

[04-12 08:04:41.382 2765:3022 I/SurfaceFlinger]
id=689 Removed 22c32a6 Splash Screen com.vtosters.lite#0 (48)

[04-12 08:04:41.385 2765:3022 I/Layer]
id=688 removeFromCurrentState AppWindowToken{f52ee64 token=Token{7497ff7 ActivityRecord{6ddff6 u0 com.vtosters.lite/.VTIconDefault t85}}}#0 (48)

[04-12 08:04:41.386 2765:3022 I/SurfaceFlinger]
id=688 Removed AppWindowToken{f52ee64 token=Token{7497ff7 ActivityRecord{6ddff6 u0 com.vtosters.lite/.VTIconDefault t85}}}#0 (48)

[04-12 08:04:41.388 2765:2765 I/Layer]
id=688[1] Destroyed AppWindowToken{f52ee64 token=Token{7497ff7 ActivityRecord{6ddff6 u0 com.vtosters.lite/.VTIconDefault t85}}}#0

[04-12 08:04:41.388 2765:2765 I/Layer]
id=689[1] Destroyed 22c32a6 Splash Screen com.vtosters.lite#0

[04-12 08:04:41.402 2765:3022 I/SurfaceFlinger]
id=690 Removed Splash Screen com.vtosters.lite#0 (44)

[04-12 08:04:41.405 2765:2765 I/Layer]
id=690[1] Destroyed Splash Screen com.vtosters.lite#0

[04-12 08:04:41.767 3080:3203 W/ActivityTaskManager]
Activity top resumed state loss timeout for ActivityRecord{6ddff6 u0 com.vtosters.lite/.VTIconDefault t-1 f}

`

**Comment by gdlbo** [comment]
https://github.com/vtosters/lite/commit/e12dcdf86ac0cbcf24e0b204a2102461902bb1b6

**Comment by max22062019** [comment]
А что мне с этим делать? Ждать обновления?
