### ISSUE TITLE
Вылет при нажатии "Найти фото"

### ISSUE THREAD

**Issue by Zaeros77** [vtosters/lite#1356]
![VTL_log_2023-06-01.14-10-33.txt](https://github.com/vtosters/lite/files/11624202/VTL_log_2023-06-01.14-10-33.txt)

**Comment by Zaeros77** [comment]
java.lang.ArrayIndexOutOfBoundsException: length=6; index=6
	at ru.vtosters.hooks.PhotoViewer.e(PhotoViewer.java:83)
	at ru.vtosters.hooks.PhotoViewer.interceptClick(PhotoViewer.java:13)
	at com.vk.ui.photoviewer.MenuController.a(Unknown Source:0)
	at com.vk.ui.photoviewer.VkAppCallback.a(VkAppCallback.kt:7)
	at com.vk.photoviewer.PhotoViewer$q.onMenuItemClick(PhotoViewer.kt:2)
	at androidx.appcompat.widget.Toolbar$1.onMenuItemClick(Toolbar.java:2)
	at androidx.appcompat.widget.ActionMenuView$MenuBuilderCallback.onMenuItemSelected(ActionMenuView.java:2)
	at androidx.appcompat.view.menu.MenuBuilder.dispatchMenuItemSelected(MenuBuilder.java:1)
	at androidx.appcompat.view.menu.MenuItemImpl.invoke(MenuItemImpl.java:2)
	at androidx.appcompat.view.menu.MenuBuilder.performItemAction(MenuBuilder.java:4)
	at androidx.appcompat.view.menu.MenuPopup.onItemClick(MenuPopup.java:6)
	at android.widget.AdapterView.performItemClick(AdapterView.java:330)
	at android.widget.AbsListView.performItemClick(AbsListView.java:1221)
	at android.widget.AbsListView$PerformClick.run(AbsListView.java:3214)
	at android.widget.AbsListView.onTouchUp(AbsListView.java:4244)
	at android.widget.AbsListView.onTouchEvent(AbsListView.java:3972)
	at androidx.appcompat.widget.DropDownListView.onTouchEvent(DropDownListView.java:5)
	at androidx.appcompat.widget.MenuPopupWindow$MenuDropDownListView.onTouchEvent(MenuPopupWindow.java:1)
	at android.view.View.dispatchTouchEvent(View.java:14857)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3125)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2798)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3131)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2812)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3131)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2812)
	at android.widget.PopupWindow$PopupDecorView.dispatchTouchEvent(PopupWindow.java:2553)
	at android.view.View.dispatchPointerEvent(View.java:15130)
	at android.view.ViewRootImpl$ViewPostImeInputStage.processPointerEvent(ViewRootImpl.java:6659)
	at android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java:6447)
	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:5888)
	at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:5945)
	at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:5911)
	at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:6076)
	at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:5919)
	at android.view.ViewRootImpl$AsyncInputStage.apply(ViewRootImpl.java:6133)
	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:5892)
	at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:5945)
	at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:5911)
	at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:5919)
	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:5892)
	at android.view.ViewRootImpl.deliverInputEvent(ViewRootImpl.java:8918)
	at android.view.ViewRootImpl.doProcessInputEvents(ViewRootImpl.java:8869)
	at android.view.ViewRootImpl.enqueueInputEvent(ViewRootImpl.java:8837)
	at android.view.ViewRootImpl$WindowInputEventReceiver.onInputEvent(ViewRootImpl.java:9051)
	at android.view.InputEventReceiver.dispatchInputEvent(InputEventReceiver.java:280)
	at android.os.MessageQueue.nativePollOnce(Native Method)
	at android.os.MessageQueue.next(MessageQueue.java:337)
	at android.os.Looper.loopOnce(Looper.java:168)
	at android.os.Looper.loop(Looper.java:299)
	at android.app.ActivityThread.main(ActivityThread.java:8250)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:556)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1045)


Device information: commit='ff8e7b7', fullVersionInfo='main-ff8e7b7-dirty', isMilkshake='false', sdkVersion='31', productName='vayu_ru', deviceName='vayu', boardName='vayu', manufacturerName='Xiaomi', brandName='POCO', MiuiUiVersionCode='13', MiuiUiVersionName='V130', MiuiUiVersionIncrementalCode='V13.0.1.0.SJURUXM', modelName='M2102J20SG'
