### ISSUE TITLE
Беседы с непрочитанными

### ISSUE THREAD

**Issue by rx1310** [vtosters/lite#140]
При открытии беседы с +3к непрочитанными клиент вылетает с ошибкой

<details>
  <summary>Лог ошибки</summary>

```
java.lang.IllegalStateException: Missing values for keyframe.
	at com.airbnb.lottie.a.b.ScaleKeyframeAnimation.b(ScaleKeyframeAnimation.java:16)
	at com.airbnb.lottie.a.b.ScaleKeyframeAnimation.a(ScaleKeyframeAnimation.java:9)
	at com.airbnb.lottie.a.b.BaseKeyframeAnimation.e(BaseKeyframeAnimation.java:125)
	at com.airbnb.lottie.a.b.TransformKeyframeAnimation.d(TransformKeyframeAnimation.java:118)
	at com.airbnb.lottie.model.layer.BaseLayer.a(BaseLayer.java:193)
	at com.airbnb.lottie.model.layer.CompositionLayer.b(CompositionLayer.java:100)
	at com.airbnb.lottie.model.layer.BaseLayer.a(BaseLayer.java:201)
	at com.airbnb.lottie.model.layer.CompositionLayer.b(CompositionLayer.java:100)
	at com.airbnb.lottie.model.layer.BaseLayer.a(BaseLayer.java:201)
	at com.airbnb.lottie.LottieDrawable.draw(LottieDrawable.java:319)
	at android.widget.ImageView.onDraw(ImageView.java:1436)
	at com.vk.im.ui.views.sticker.ImStickerAnimationView.onDraw(ImStickerAnimationView.kt:72)
	at android.view.View.draw(View.java:22357)
	at android.view.View.buildDrawingCacheImpl(View.java:21630)
	at android.view.View.buildDrawingCache(View.java:21490)
	at android.view.View.draw(View.java:22080)
	at android.view.ViewGroup.drawChild(ViewGroup.java:4516)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4277)
	at android.view.View.updateDisplayListIfDirty(View.java:21224)
	at android.view.View.draw(View.java:22088)
	at android.view.ViewGroup.drawChild(ViewGroup.java:4516)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4277)
	at android.view.View.updateDisplayListIfDirty(View.java:21224)
	at android.view.View.draw(View.java:22088)
	at android.view.ViewGroup.drawChild(ViewGroup.java:4516)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4277)
	at android.view.View.draw(View.java:22360)
	at android.view.View.updateDisplayListIfDirty(View.java:21233)
	at android.view.View.draw(View.java:22088)
	at android.view.ViewGroup.drawChild(ViewGroup.java:4516)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4277)
	at android.view.View.updateDisplayListIfDirty(View.java:21224)
	at android.view.View.draw(View.java:22088)
	at android.view.ViewGroup.drawChild(ViewGroup.java:4516)
	at android.support.v7.widget.RecyclerView.drawChild(RecyclerView.java:4703)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4277)
	at android.view.View.draw(View.java:22360)
	at android.support.v7.widget.RecyclerView.draw(RecyclerView.java:4107)
	at android.view.View.updateDisplayListIfDirty(View.java:21233)
	at android.view.View.draw(View.java:22088)
	at android.view.ViewGroup.drawChild(ViewGroup.java:4516)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4277)
	at android.view.View.updateDisplayListIfDirty(View.java:21224)
	at android.view.View.draw(View.java:22088)
	at android.view.ViewGroup.drawChild(ViewGroup.java:4516)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4277)
	at android.view.View.updateDisplayListIfDirty(View.java:21224)
	at android.view.View.draw(View.java:22088)
	at android.view.ViewGroup.drawChild(ViewGroup.java:4516)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4277)
	at android.view.View.draw(View.java:22360)
	at android.view.View.updateDisplayListIfDirty(View.java:21233)
	at android.view.View.draw(View.java:22088)
	at android.view.ViewGroup.drawChild(ViewGroup.java:4516)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4277)
	at android.view.View.draw(View.java:22360)
	at android.view.View.updateDisplayListIfDirty(View.java:21233)
	at android.view.View.draw(View.java:22088)
	at android.view.ViewGroup.drawChild(ViewGroup.java:4516)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4277)
	at android.view.View.updateDisplayListIfDirty(View.java:21224)
	at android.view.View.draw(View.java:22088)
	at android.view.ViewGroup.drawChild(ViewGroup.java:4516)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4277)
	at android.view.View.draw(View.java:22360)
	at android.support.v4.view.ViewPager.draw(ViewPager.java:2420)
	at android.view.View.updateDisplayListIfDirty(View.java:21233)
	at android.view.View.draw(View.java:22088)
	at android.view.ViewGroup.drawChild(ViewGroup.java:4516)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4277)
	at android.view.View.updateDisplayListIfDirty(View.java:21224)
	at android.view.View.draw(View.java:22088)
	at android.view.ViewGroup.drawChild(ViewGroup.java:4516)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4277)
	at android.view.View.updateDisplayListIfDirty(View.java:21224)
	at android.view.View.draw(View.java:22088)
	at android.view.ViewGroup.drawChild(ViewGroup.java:4516)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4277)
	at android.view.View.updateDisplayListIfDirty(View.java:21224)
	at android.view.View.draw(View.java:22088)
	at android.view.ViewGroup.drawChild(ViewGroup.java:4516)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4277)
	at android.view.View.updateDisplayListIfDirty(View.java:21224)
	at android.view.View.draw(View.java:22088)
	at android.view.ViewGroup.drawChild(ViewGroup.java:4516)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4277)
	at android.view.View.draw(View.java:22360)
	at com.android.internal.policy.DecorView.draw(DecorView.java:806)
	at android.view.View.updateDisplayListIfDirty(View.java:21233)
	at android.view.ThreadedRenderer.updateViewTreeDisplayList(ThreadedRenderer.java:559)
	at android.view.ThreadedRenderer.updateRootDisplayList(ThreadedRenderer.java:565)
	at android.view.ThreadedRenderer.draw(ThreadedRenderer.java:642)
	at android.view.ViewRootImpl.draw(ViewRootImpl.java:4106)
	at android.view.ViewRootImpl.performDraw(ViewRootImpl.java:3833)
	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:3104)
	at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1948)
	at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:8181)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:972)
	at android.view.Choreographer.doCallbacks(Choreographer.java:796)
	at android.view.Choreographer.doFrame(Choreographer.java:731)
	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:957)
	at android.os.Handler.handleCallback(Handler.java:938)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:223)
	at android.app.ActivityThread.main(ActivityThread.java:7664)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)


Device{sdkVersion=30, productName='vayu_global', deviceName='vayu', boardName='msmnile', cpuAbi='armeabi-v7a', manufacturerName='Xiaomi', brandName='POCO', modelName='M2102J20SG'}
 VTL Version: 2.0 DEV, build: 2f9cf47
```

</details>

**Comment by rx1310** [comment]
Также хотелось бы кнопочку для "прочтения" диалога, как это сделано в Sova, к примеру:
![IMG_20220412_165204.png](https://user-images.githubusercontent.com/33829769/162977849-fed9bda6-d469-4de7-90ee-3b7619e1e9df.png)
