### ISSUE TITLE
Произошла ошибка в работе VTLite

### ISSUE THREAD

**Issue by pelageech** [vtosters/lite#1400]
**Опишите сам баг**
При использовании вылезла фатальная ошибка.

**Опишите действия для воспроизведения ошибки**
Переключился с одного приложения на VTLite и тут же нажал на вкладку сообщения, после чего внезапный вылет.

**Скриншот ошибки**
![IMG_20230707_143102](https://github.com/vtosters/lite/assets/91509036/7f62cc32-65a9-47af-a714-1138c546b0ba)

**Скопируйте сюда информацию об устройстве**
См. Логи

**Дополнительная информация о баге или мыслях почему оно может происходить (если есть)**

Логи:
```
java.lang.ArrayIndexOutOfBoundsException: length=4164; index=4164
	at java.util.ArrayList.add(ArrayList.java:468)
	at s8.d(VTVerifications.java:25)
	at s8.c(VTVerifications.java:25)
	at L5.a(OTAUtils.java:28)
	at okhttp3.RealCall$b.d(RealCall.java:5)
	at okhttp3.f0.NamedRunnable.run(NamedRunnable.java:3)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
	at java.lang.Thread.run(Thread.java:764)


Device information: commit='cdaf790', fullVersionInfo='main-cdaf790-dirty', isMilkshake='true', sdkVersion='28', productName='willow_eea', deviceName='willow', boardName='willow', manufacturerName='Xiaomi', brandName='xiaomi', MiuiUiVersionCode='9', MiuiUiVersionName='V11', MiuiUiVersionIncrementalCode='V11.0.11.0.PCXEUXM', modelName='Redmi Note 8T'
```

**Comment by gdlbo** [comment]
исправлено
