### ISSUE TITLE
При открытии VK NFT через вкладку "Мини-приложения" вылетает VTLite

### ISSUE THREAD

**Issue by Coffeebar13** [vtosters/lite#1409]
**Опишите сам баг**
При открытии VK NFT через вкладку "Мини-приложения" вылетает VTLite

**Опишите действия для воспроизведения ошибки**
1. Открыть "Сервисы"
2. Открыть вкладку "Мини-приложения"
3. Зайти в VK NFT

**Опишите ожидаемый результат**
Должно открыться приложение VK NFT

**Скриншот ошибки**
![Screenshot_20230711_165406_Chrome](https://github.com/vtosters/lite/assets/60733236/7e241167-7cc9-4ae3-a378-82080c0837ed)

**Информация об устройстве:** 

- Commit: cdaf790
- Full Version Information: main-cdaf790-dirty
- Android SDK: 33
- Product: a73xqxx
- Device: a73xq
- Board: lahaina
- Manufacturer: samsung
- Brand: samsung
- Model: SM-A736B
- OneUi Major Version: 5
- OneUi Minor Version: 1.0

**Почему может происходить данный баг**
VTLite не может открыть сайт внутри мини-приложения

**Comment by Daniska116** [comment]
Такая же проблема. Лог: java.lang.IllegalAccessError: Method 'java.lang.String com.vtosters.lite.general.fragments.GamesListFragment.c5()' is inaccessible to class 'com.vtosters.lite.fragments.MyGamesListFragment$adapter$2' (declaration of 'com.vtosters.lite.fragments.MyGamesListFragment$adapter$2' appears in base.apk!classes4.dex)
	at com.vtosters.lite.fragments.MyGamesListFragment$adapter$2.invoke(MyGamesListFragment.kt:2)
	at com.vtosters.lite.fragments.MyGamesListFragment$adapter$2.invoke(MyGamesListFragment.kt:1)
	at kotlin.SynchronizedLazyImpl.getValue(LazyJVM.kt:6)
	at com.vtosters.lite.fragments.MyGamesListFragment.Y4(Unknown Source:7)
	at com.vtosters.lite.fragments.MyGamesListFragment.Y4(MyGamesListFragment.kt:1)
	at me.grishka.appkit.fragments.BaseRecyclerFragment.a(BaseRecyclerFragment.java:22)
	at com.vtosters.lite.general.fragments.VKRecyclerFragment.a(VKRecyclerFragment.java:1)
	at com.vtosters.lite.general.fragments.GamesListFragment.a(GamesListFragment.java:4)
	at me.grishka.appkit.fragments.LoaderFragment.onCreateView(LoaderFragment.java:4)
	at androidx.fragment.app.Fragment.performCreateView(Fragment.java:6)
	at androidx.fragment.app.HackSupportFragment.createView$libfragments_release(HackSupportFragment.kt:1)
	at com.vk.core.fragments.FragmentImpl.createView$libfragments_release(FragmentImpl.kt:7)
	at androidx.fragment.app.HackSupportFragment.performCreateView(HackSupportFragment.kt:1)
	at androidx.fragment.app.FragmentManagerImpl.moveToState(FragmentManager.java:65)
	at androidx.fragment.app.FragmentManagerImpl.moveFragmentToExpectedState(FragmentManager.java:6)
	at androidx.fragment.app.FragmentManagerImpl.moveToState(FragmentManager.java:150)
	at androidx.fragment.app.BackStackRecord.executeOps(BackStackRecord.java:24)
	at androidx.fragment.app.FragmentManagerImpl.executeOps(FragmentManager.java:6)
	at androidx.fragment.app.FragmentManagerImpl.executeOpsTogether(FragmentManager.java:14)
	at androidx.fragment.app.FragmentManagerImpl.removeRedundantOperationsAndExecute(FragmentManager.java:10)
	at androidx.fragment.app.FragmentManagerImpl.execSingleAction(FragmentManager.java:5)
	at androidx.fragment.app.BackStackRecord.commitNowAllowingStateLoss(BackStackRecord.java:2)
	at com.vk.core.fragments.j.b.ParentSupportFragmentManager.c(ParentSupportFragmentManager.kt:1)
	at com.vk.core.fragments.FragmentNavigationController.a(FragmentNavigationController.kt:57)
	at com.vk.core.fragments.FragmentNavigationController.a(FragmentNavigationController.kt:2)
	at com.vk.core.fragments.FragmentNavigationController$show$1.invoke(FragmentNavigationController.kt:7)
	at com.vk.core.fragments.FragmentNavigationController$show$1.invoke(FragmentNavigationController.kt:1)
	at com.vk.core.fragments.FragmentNavigationController.a(FragmentNavigationController.kt:77)
	at com.vk.core.fragments.FragmentNavigationController.a(FragmentNavigationController.kt:8)
	at com.vk.navigation.NavigationDelegate.a(NavigationDelegate.kt:19)
	at com.vk.navigation.NavigationDelegateBottom$g.run(NavigationDelegateBottom.kt:1)
	at com.vk.core.util.ThreadUtils.b(ThreadUtils.kt:5)
	at com.vk.core.util.ThreadUtils.e(ThreadUtils.kt:1)
	at com.vk.navigation.NavigationDelegateBottom.a(NavigationDelegateBottom.kt:83)
	at com.vk.navigation.Navigator.a(Navigator.kt:30)
	at com.vk.navigation.Navigator.a(Navigator.kt:27)
	at com.vk.navigation.Navigator.a(Navigator.kt:6)
	at com.vtosters.lite.ui.holder.gamepage.MyGamesSectionHolder$b.onClick(MyGamesSectionHolder.kt:5)
	at android.view.View.performClick(Unknown Source:17)
	at android.view.View.performClickInternal(Unknown Source:3)
	at android.view.View.-$$Nest$mperformClickInternal(Unknown Source:0)
	at android.view.View$PerformClick.run(Unknown Source:8)
	at android.os.Handler.handleCallback(Unknown Source:2)
	at android.os.Handler.dispatchMessage(Unknown Source:4)
	at android.os.Looper.loopOnce(Unknown Source:182)
	at android.os.Looper.loop(Unknown Source:82)
	at android.app.ActivityThread.main(Unknown Source:123)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(Unknown Source:11)
	at com.android.internal.os.ZygoteInit.main(Unknown Source:312)


Device information: commit='cdaf790', fullVersionInfo='main-cdaf790-dirty', isMilkshake='true', sdkVersion='33', productName='umi', deviceName='umi', boardName='umi', manufacturerName='Xiaomi', brandName='Xiaomi', MiuiUiVersionCode='14', MiuiUiVersionName='V140', MiuiUiVersionIncrementalCode='V14.0.3.0.TJBCNXM', modelName='Mi 10'
