### ISSUE TITLE
Проблема сообщения когда открываешь стикеры 

### ISSUE THREAD

**Issue by isus203** [vtosters/lite#1417]
Когда заходишь в сообщения и нажимаешь на иконку стикеров для выбора и приложения на долго зависает 
 
вот лог ошибки

java.lang.IndexOutOfBoundsException: Index: 0, Size: 0
	at java.util.ArrayList.get(ArrayList.java:437)
	at androidx.viewpager.widget.ViewPager.performDrag(ViewPager.java:7)
	at androidx.viewpager.widget.ViewPager.onTouchEvent(ViewPager.java:36)
	at android.view.View.dispatchTouchEvent(View.java:14584)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3182)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2822)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3188)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2836)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3188)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2836)
	at android.widget.PopupWindow$PopupDecorView.dispatchTouchEvent(PopupWindow.java:2566)
	at android.view.View.dispatchPointerEvent(View.java:14850)
	at android.view.ViewRootImpl$ViewPostImeInputStage.processPointerEvent(ViewRootImpl.java:6346)
	at android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java:6137)
	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:5622)
	at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:5679)
	at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:5645)
	at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:5797)
	at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:5653)
	at android.view.ViewRootImpl$AsyncInputStage.apply(ViewRootImpl.java:5854)
	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:5626)
	at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:5679)
	at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:5645)
	at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:5653)
	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:5626)
	at android.view.ViewRootImpl.deliverInputEvent(ViewRootImpl.java:8504)
	at android.view.ViewRootImpl.doProcessInputEvents(ViewRootImpl.java:8455)
	at android.view.ViewRootImpl.enqueueInputEvent(ViewRootImpl.java:8406)
	at android.view.ViewRootImpl$WindowInputEventReceiver.onInputEvent(ViewRootImpl.java:8644)
	at android.view.InputEventReceiver.dispatchInputEvent(InputEventReceiver.java:282)
	at android.os.MessageQueue.nativePollOnce(Native Method)
	at android.os.MessageQueue.next(MessageQueue.java:335)
	at android.os.Looper.loop(Looper.java:193)
	at android.app.ActivityThread.main(ActivityThread.java:7864)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:620)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1011)

Device information: commit='cdaf790', fullVersionInfo='main-cdaf790-dirty', isMilkshake='true', sdkVersion='30', productName='galahad_ru', deviceName='galahad', boardName='galahad', manufacturerName='Xiaomi', brandName='Redmi', MiuiUiVersionCode='12', MiuiUiVersionName='V130', MiuiUiVersionIncrementalCode='+isus203+', modelName='M2004J19C'

**Comment by ayonovdenizs** [comment]
Пересоздайте issue по шаблону
