### ISSUE TITLE
Ошибка обновлении/просмотра ленты рекомендаций

### ISSUE THREAD

**Issue by rasbayri** [vtosters/lite#1437]
java.lang.IllegalStateException: Layout state should be one of 100 but it is 10
	at androidx.recyclerview.widget.RecyclerView$State.assertLayoutStep(RecyclerView.java:4)
	at androidx.recyclerview.widget.RecyclerView.dispatchLayoutStep3(RecyclerView.java:1)
	at androidx.recyclerview.widget.RecyclerView.dispatchLayout(RecyclerView.java:15)
	at androidx.recyclerview.widget.RecyclerView.consumePendingUpdateOperations(RecyclerView.java:21)
	at androidx.recyclerview.widget.RecyclerView$ViewFlinger.run(RecyclerView.java:4)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1142)
	at android.view.Choreographer.doCallbacks(Choreographer.java:946)
	at android.view.Choreographer.doFrame(Choreographer.java:870)
	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1127)
	at android.os.Handler.handleCallback(Handler.java:938)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:210)
	at android.os.Looper.loop(Looper.java:299)
	at android.app.ActivityThread.main(ActivityThread.java:8293)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:556)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1045)

Device information: commit='cf17ed6', fullVersionInfo='main-cf17ed6-dirty', isMilkshake='false', sdkVersion='31', productName='lmi_eea', deviceName='lmi', boardName='lmi', manufacturerName='Xiaomi', brandName='POCO', MiuiUiVersionCode='14', MiuiUiVersionName='V140', MiuiUiVersionIncrementalCode='V14.0.1.0.SJKEUXM', modelName='POCO F2 Pro'

**Comment by gdlbo** [comment]
вк баг
