### ISSUE TITLE
Ошибка в чате личных сообщений

### ISSUE THREAD

**Issue by Aynekko** [vtosters/lite#1523]
**Опишите сам баг**
При написании сообщения "Годно" вылезает подсказка со стикерами и тут же вылетает

**Опишите действия для воспроизведения ошибки**
Описано выше, воспроизводится в 100% случаев.

Лог после вылета:

java.lang.RuntimeException: Font asset not found fonts/Times New Roman.ttf
	at android.graphics.Typeface.createFromAsset(Typeface.java:784)
	at com.airbnb.lottie.s.FontAssetManager.a(FontAssetManager.java:11)
	at com.airbnb.lottie.s.FontAssetManager.a(FontAssetManager.java:4)
	at com.airbnb.lottie.LottieDrawable.a(LottieDrawable.java:63)
	at com.airbnb.lottie.model.layer.TextLayer.a(TextLayer.java:27)
	at com.airbnb.lottie.model.layer.TextLayer.b(TextLayer.java:23)
	at com.airbnb.lottie.model.layer.BaseLayer.a(BaseLayer.java:39)
	at com.airbnb.lottie.model.layer.CompositionLayer.b(CompositionLayer.java:9)
	at com.airbnb.lottie.model.layer.BaseLayer.a(BaseLayer.java:39)
	at com.airbnb.lottie.model.layer.CompositionLayer.b(CompositionLayer.java:9)
	at com.airbnb.lottie.model.layer.BaseLayer.a(BaseLayer.java:39)
	at com.airbnb.lottie.LottieDrawable.draw(LottieDrawable.java:16)
	at android.widget.ImageView.onDraw(ImageView.java:1367)
	at com.vk.stickers.views.animation.VKAnimationView.onDraw(VKAnimationView.kt:2)
	at android.view.View.draw(View.java:19310)
	at android.view.View.updateDisplayListIfDirty(View.java:18231)
	at android.view.View.draw(View.java:19029)
	at android.view.ViewGroup.drawChild(ViewGroup.java:4437)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4216)
	at android.view.View.updateDisplayListIfDirty(View.java:18222)
	at android.view.View.draw(View.java:19029)
	at android.view.ViewGroup.drawChild(ViewGroup.java:4437)
	at androidx.recyclerview.widget.RecyclerView.drawChild(RecyclerView.java:1)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4216)
	at android.view.View.draw(View.java:19313)
	at androidx.recyclerview.widget.RecyclerView.draw(RecyclerView.java:1)
	at android.view.View.updateDisplayListIfDirty(View.java:18231)
	at android.view.View.draw(View.java:19029)
	at android.view.ViewGroup.drawChild(ViewGroup.java:4437)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4216)
	at android.view.View.updateDisplayListIfDirty(View.java:18222)
	at android.view.View.draw(View.java:19029)
	at android.view.ViewGroup.drawChild(ViewGroup.java:4437)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4216)
	at android.view.View.updateDisplayListIfDirty(View.java:18222)
	at android.view.ThreadedRenderer.updateViewTreeDisplayList(ThreadedRenderer.java:676)
	at android.view.ThreadedRenderer.updateRootDisplayList(ThreadedRenderer.java:682)
	at android.view.ThreadedRenderer.draw(ThreadedRenderer.java:811)
	at android.view.ViewRootImpl.draw(ViewRootImpl.java:3077)
	at android.view.ViewRootImpl.performDraw(ViewRootImpl.java:2881)
	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2420)
	at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1453)
	at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:7577)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1049)
	at android.view.Choreographer.doCallbacks(Choreographer.java:849)
	at android.view.Choreographer.doFrame(Choreographer.java:768)
	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1032)
	at android.os.Handler.handleCallback(Handler.java:790)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:164)
	at android.app.ActivityThread.main(ActivityThread.java:6558)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:469)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:826)

Device information: commit='f5180f6', fullVersionInfo='main-f5180f6-dirty', isMilkshake='true', sdkVersion='27', productName='bbb100india', deviceName='bbb100', boardName='msm8953', manufacturerName='BlackBerry', brandName='blackberry', modelName='BBB100-7'

**Comment by gdlbo** [comment]
в системе отсутствуют необходимые шрифты, могу только посочувствовать и предложить установить кастомную прошивку
