### ISSUE TITLE
При зажимании на стикер VTL крашится 

### ISSUE THREAD

**Issue by egf0x** [vtosters/lite#158]
Выбираю стикер, зажимаю, для его предпросмотра и VTL крашится, прикрепляю скриншот с ошибкой
![Screenshot_20220415-140917](https://user-images.githubusercontent.com/97127436/163564321-2cd010dd-ac7c-4867-b55f-a6ab4ff39273.png)

**Comment by egf0x** [comment]
вот полностью содержимое лог-файла:

java.lang.IllegalStateException: Missing values for keyframe.
	at com.airbnb.lottie.a.b.FloatKeyframeAnimation.b(FloatKeyframeAnimation.java:16)
	at com.airbnb.lottie.a.b.FloatKeyframeAnimation.a(FloatKeyframeAnimation.java:8)
	at com.airbnb.lottie.a.b.BaseKeyframeAnimation.e(BaseKeyframeAnimation.java:125)
	at com.airbnb.lottie.a.b.TransformKeyframeAnimation.d(TransformKeyframeAnimation.java:113)
	at com.airbnb.lottie.model.layer.BaseLayer.a(BaseLayer.java:199)
	at com.airbnb.lottie.model.layer.CompositionLayer.b(CompositionLayer.java:100)
	at com.airbnb.lottie.model.layer.BaseLayer.a(BaseLayer.java:201)
	at com.airbnb.lottie.model.layer.CompositionLayer.b(CompositionLayer.java:100)
	at com.airbnb.lottie.model.layer.BaseLayer.a(BaseLayer.java:201)
	at com.airbnb.lottie.LottieDrawable.draw(LottieDrawable.java:319)
	at android.widget.ImageView.onDraw(ImageView.java:1436)
	at com.vk.stickers.views.animation.VKAnimationView.onDraw(VKAnimationView.kt:88)
	at android.view.View.draw(View.java:22350)
	at android.view.View.buildDrawingCacheImpl(View.java:21623)
	at android.view.View.buildDrawingCache(View.java:21483)
	at android.view.View.draw(View.java:22073)
	at android.view.ViewGroup.drawChild(ViewGroup.java:4516)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4277)
	at android.view.View.updateDisplayListIfDirty(View.java:21217)
	at android.view.View.draw(View.java:22081)
	at android.view.ViewGroup.drawChild(ViewGroup.java:4516)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4277)
	at android.view.View.draw(View.java:22353)
	at android.support.v4.view.ViewPager.draw(ViewPager.java:2420)
	at android.view.View.updateDisplayListIfDirty(View.java:21226)
	at android.view.View.draw(View.java:22081)
	at android.view.ViewGroup.drawChild(ViewGroup.java:4516)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4277)
	at android.view.View.draw(View.java:22353)
	at android.view.View.updateDisplayListIfDirty(View.java:21226)
	at android.view.View.draw(View.java:22081)
	at android.view.ViewGroup.drawChild(ViewGroup.java:4516)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4277)
	at android.view.View.draw(View.java:22353)
	at android.view.View.updateDisplayListIfDirty(View.java:21226)
	at android.view.View.draw(View.java:22081)
	at android.view.ViewGroup.drawChild(ViewGroup.java:4516)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4277)
	at android.view.View.updateDisplayListIfDirty(View.java:21217)
	at android.view.ThreadedRenderer.updateViewTreeDisplayList(ThreadedRenderer.java:559)
	at android.view.ThreadedRenderer.updateRootDisplayList(ThreadedRenderer.java:565)
	at android.view.ThreadedRenderer.draw(ThreadedRenderer.java:642)
	at android.view.ViewRootImpl.draw(ViewRootImpl.java:4106)
	at android.view.ViewRootImpl.performDraw(ViewRootImpl.java:3833)
	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:3104)
	at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1948)
	at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:8177)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:972)
	at android.view.Choreographer.doCallbacks(Choreographer.java:796)
	at android.view.Choreographer.doFrame(Choreographer.java:731)
	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:957)
	at android.os.Handler.handleCallback(Handler.java:938)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:223)
	at android.app.ActivityThread.main(ActivityThread.java:7664)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)


Device{sdkVersion=30, productName='aosp_lime', deviceName='lemon', boardName='lemon', cpuAbi='armeabi-v7a', manufacturerName='Xiaomi', brandName='Redmi', modelName='Redmi 9T NFC'}
 VTL Version: 2.0 DEV, build: 2f9cf47
