### ISSUE TITLE
вылет из приложения

### ISSUE THREAD

**Issue by NEOWHS** [vtosters/lite#1611]
kotlin.UninitializedPropertyAccessException: lateinit property album has not been initialized
	at com.vk.profile.ui.photos.photo_list.PhotoListFragmentPresenter.c(PhotoListFragmentPresenter.kt:1)
	at com.vk.profile.ui.photos.photo_list.PhotoListFragmentNew$g.a(PhotoListFragmentNew.kt:1)
	at com.vk.ui.photoviewer.MenuController.e(MenuController.kt:2)
	at com.vk.ui.photoviewer.MenuController.e(MenuController.kt:1)
	at com.vk.ui.photoviewer.MenuController$makeFullPopup$$inlined$let$lambda$4.invoke(MenuController.kt:2)
	at com.vk.ui.photoviewer.MenuController$makeFullPopup$$inlined$let$lambda$4.invoke(MenuController.kt:1)
	at com.vk.core.dialogs.actionspopup.ActionsPopup$b$b.a(ActionsPopup.kt:2)
	at com.vk.core.dialogs.actionspopup.ActionsPopup$b$b.a(ActionsPopup.kt:1)
	at com.vk.core.dialogs.adapter.ModalAdapter$c.onClick(ModalAdapter.kt:3)
	at com.vk.core.extensions.ViewGroupExtKt$a.onClick(ViewGroupExt.kt:1)
	at android.view.View.performClick(View.java:7729)
	at android.view.View.performClickInternal(View.java:7706)
	at android.view.View.-$$Nest$mperformClickInternal(Unknown Source:0)
	at android.view.View$PerformClick.run(View.java:30484)
	at android.os.Handler.handleCallback(Handler.java:959)
	at android.os.Handler.dispatchMessage(Handler.java:100)
	at android.os.Looper.loopOnce(Looper.java:232)
	at android.os.Looper.loop(Looper.java:317)
	at android.app.ActivityThread.main(ActivityThread.java:8501)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:552)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:878)

Device information: commit='fd17e2b', fullVersionInfo='main-fd17e2b-dirty', isMilkshake='true', sdkVersion='34', productName='oriole', deviceName='oriole', boardName='oriole', manufacturerName='Google', brandName='google', modelName='Pixel 6'

**Comment by danyyok** [comment]
@NEOWHS Пересоздайте Issue по шаблону прикрепив информацию об устройсте
