### ISSUE TITLE
Ошибка авторизации при входе в аккаунт

### ISSUE THREAD

**Issue by Tahgolov** [vtosters/lite#1619]
**Описание**
Примерно с 12 июня наблюдается проблема входа в аккаунт в VTLite и оригинальных версиях < ~6.16. 
 
**Воспроизведение**
1. Попытаться войти в аккаунт на версиях < ~6.16.

**Лог**
```
VKApiExecutionException{code=-2147483648, extra=null, method=execute.getUserInfo, executeErrors=[VKApiExecutionException{code=3, extra=null, method=newsfeed.getPostTopics, executeErrors=null, super=com.vk.api.sdk.exceptions.VKApiExecutionException: Unknown method passed | by [newsfeed.getPostTopics]}], super=com.vk.api.sdk.exceptions.VKApiExecutionException: }
	at com.vk.api.sdk.internal.VKErrorUtils.a(VKErrorUtils.kt:30)
	at com.vk.api.sdk.internal.VKErrorUtils.a(VKErrorUtils.kt:22)
	at com.vk.api.sdk.utils.ApiExt.a(ApiExt.kt:4)
	at com.vk.api.sdk.chain.MethodChainCall.a(MethodChainCall.kt:22)
	at com.vk.api.internal.chain.InternalMethodChainCall.a(InternalMethodChainCall.kt:21)
	at com.vk.api.sdk.chain.MethodChainCall.a(MethodChainCall.kt:15)
	at com.vk.api.sdk.chain.ValidationHandlerChainCall.a(ValidationHandlerChainCall.kt:2)
	at com.vk.api.sdk.chain.InvalidCredentialsObserverChainCall.a(InvalidCredentialsObserverChainCall.kt:1)
	at com.vk.api.sdk.chain.TooManyRequestRetryChainCall.a(TooManyRequestRetryChainCall.kt:4)
	at com.vk.api.sdk.chain.InternalErrorRetryChainCall.a(InternalErrorRetryChainCall.kt:6)
	at com.vk.api.internal.chain.TokenConfirmationHandlerChainCall.a(TokenConfirmationHandlerChainCall.kt:2)
	at com.vk.api.internal.ApiManager.a(ApiManager.kt:41)
	at com.vk.api.sdk.VKApiManager.b(VKApiManager.kt:3)
	at com.vk.api.base.ApiRequest.b(ApiRequest.kt:20)
	at com.vk.api.sdk.internal.ApiCommand.a(ApiCommand.kt:1)
	at com.vk.api.base.ApiRequest$f.a(ApiRequest.kt:3)
	at io.reactivex.internal.operators.observable.ObservableCreate.b(ObservableCreate.java:3)
	at io.reactivex.Observable.a(Observable.java:152)
	at io.reactivex.internal.operators.observable.ObservableDoOnEach.b(ObservableDoOnEach.java:1)
	at io.reactivex.Observable.a(Observable.java:152)
	at io.reactivex.internal.operators.observable.ObservableSubscribeOn$a.run(ObservableSubscribeOn.java:1)
	at io.reactivex.internal.schedulers.ScheduledDirectTask.call(ScheduledDirectTask.java:3)
	at io.reactivex.internal.schedulers.ScheduledDirectTask.call(ScheduledDirectTask.java:1)
	at java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:644)
	at java.lang.Thread.run(Thread.java:1012)```

**Comment by Myakishsow-dev** [comment]
У меня аналогичная проблема, вы нашли решение ?

**Comment by Tahgolov** [comment]
@Myakishsow-dev я его сделал, посмотрите коммит https://github.com/Tahgolov/lite/commit/917966646b33086316cdddc7185e2b98abd047eb

**Comment by Myakishsow-dev** [comment]
Спасибо тебе большое @Tahgolov
