### ISSUE TITLE
Невозможно установить фотографию.

### ISSUE THREAD

**Issue by ghosterfirst** [vtosters/lite#22]
Крашится, когда пытаешься нажать на кнопку «Редактировать» или «Готово».

**Comment by gdlbo** [comment]
Если проблема актуальна - дайте логи

**Comment by ghosterfirst** [comment]
При нажатии «Редактировать».
Лог:
android.view.InflateException: Binary XML file line #26 in com.vtosters.lite:layout/picker_screen_image_editor: parent=FrameLayout:com.vtosters.lite:id/fl_actions_panel, view=com.vk.attachpicker.widget.AnimatableTextView:com.vtosters.lite:id/tv_attach
Caused by: android.view.InflateException: parent=FrameLayout:com.vtosters.lite:id/fl_actions_panel, view=com.vk.attachpicker.widget.AnimatableTextView:com.vtosters.lite:id/tv_attach
	at com.vk.core.ui.VKUILayoutFactory.onCreateView(VKUILayoutFactory.kt:40)
	at android.view.LayoutInflater.tryCreateView(LayoutInflater.java:1059)
	at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:995)
	at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:959)
	at android.view.LayoutInflater.rInflate(LayoutInflater.java:1121)
	at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:1082)
	at android.view.LayoutInflater.rInflate(LayoutInflater.java:1124)
	at android.view.LayoutInflater.inflate(LayoutInflater.java:654)
	at android.view.LayoutInflater.inflate(LayoutInflater.java:532)
	at android.view.LayoutInflater.inflate(LayoutInflater.java:479)
	at com.vk.attachpicker.f.EditorScreen.a(EditorScreen.java:236)
	at com.vk.core.simplescreen.BaseScreen.b(BaseScreen.java:26)
	at com.vk.core.simplescreen.ScreenContainer.a(ScreenContainer.java:105)
	at com.vk.core.simplescreen.BaseScreen.a(BaseScreen.java:83)
	at com.vk.attachpicker.f.ViewerScreen$16$2.run(ViewerScreen.java:312)
	at com.vk.attachpicker.f.ViewerScreen$19.onAnimationEnd(ViewerScreen.java:449)
	at android.animation.Animator$AnimatorListener.onAnimationEnd(Animator.java:554)
	at android.animation.AnimatorSet.endAnimation(AnimatorSet.java:1301)
	at android.animation.AnimatorSet.doAnimationFrame(AnimatorSet.java:1086)
	at android.animation.AnimationHandler.doAnimationFrame(AnimationHandler.java:146)
	at android.animation.AnimationHandler.access$100(AnimationHandler.java:37)
	at android.animation.AnimationHandler$1.doFrame(AnimationHandler.java:54)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1008)
	at android.view.Choreographer.doCallbacks(Choreographer.java:809)
	at android.view.Choreographer.doFrame(Choreographer.java:740)
	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:995)
	at android.os.Handler.handleCallback(Handler.java:938)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:246)
	at android.app.ActivityThread.main(ActivityThread.java:8633)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:602)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1130)
Caused by: android.view.InflateException: Binary XML file line #26 in com.vtosters.lite:layout/picker_screen_image_editor: Error inflating class com.vk.attachpicker.widget.AnimatableTextView
Caused by: java.lang.reflect.InvocationTargetException
	at java.lang.reflect.Constructor.newInstance0(Native Method)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:343)
	at android.view.LayoutInflater.createView(LayoutInflater.java:852)
	at android.view.LayoutInflater.createView(LayoutInflater.java:774)
	at com.vk.core.ui.VKLayoutInflater.a(VKLayoutInflater.kt:71)
	at com.vk.core.ui.VKUILayoutFactory.onCreateView(VKUILayoutFactory.kt:35)
	at android.view.LayoutInflater.tryCreateView(LayoutInflater.java:1059)
	at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:995)
	at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:959)
	at android.view.LayoutInflater.rInflate(LayoutInflater.java:1121)
	at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:1082)
	at android.view.LayoutInflater.rInflate(LayoutInflater.java:1124)
	at android.view.LayoutInflater.inflate(LayoutInflater.java:654)
	at android.view.LayoutInflater.inflate(LayoutInflater.java:532)
	at android.view.LayoutInflater.inflate(LayoutInflater.java:479)
	at com.vk.attachpicker.f.EditorScreen.a(EditorScreen.java:236)
	at com.vk.core.simplescreen.BaseScreen.b(BaseScreen.java:26)
	at com.vk.core.simplescreen.ScreenContainer.a(ScreenContainer.java:105)
	at com.vk.core.simplescreen.BaseScreen.a(BaseScreen.java:83)
	at com.vk.attachpicker.f.ViewerScreen$16$2.run(ViewerScreen.java:312)
	at com.vk.attachpicker.f.ViewerScreen$19.onAnimationEnd(ViewerScreen.java:449)
	at android.animation.Animator$AnimatorListener.onAnimationEnd(Animator.java:554)
	at android.animation.AnimatorSet.endAnimation(AnimatorSet.java:1301)
	at android.animation.AnimatorSet.doAnimationFrame(AnimatorSet.java:1086)
	at android.animation.AnimationHandler.doAnimationFrame(AnimationHandler.java:146)
	at android.animation.AnimationHandler.access$100(AnimationHandler.java:37)
	at android.animation.AnimationHandler$1.doFrame(AnimationHandler.java:54)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1008)
	at android.view.Choreographer.doCallbacks(Choreographer.java:809)
	at android.view.Choreographer.doFrame(Choreographer.java:740)
	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:995)
	at android.os.Handler.handleCallback(Handler.java:938)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:246)
	at android.app.ActivityThread.main(ActivityThread.java:8633)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:602)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1130)
Caused by: java.lang.UnsupportedOperationException: Failed to resolve attribute at index 5: TypedValue{t=0x2/d=0x7f040022 a=-1}
	at android.content.res.TypedArray.getColorStateList(TypedArray.java:597)
	at android.widget.TextView.readTextAppearance(TextView.java:4326)
	at android.widget.TextView.<init>(TextView.java:1360)
	at android.widget.TextView.<init>(TextView.java:1241)
	at android.support.v7.widget.AppCompatTextView.<init>(AppCompatTextView.java:76)
	at android.support.v7.widget.AppCompatTextView.<init>(AppCompatTextView.java:72)
	at com.vk.attachpicker.widget.AnimatableTextView.<init>(AnimatableTextView.java:22)
	... 38 more


Device{sdkVersion=30, productName='a01qser', deviceName='a01q', boardName='QC_Reference_Phone', cpuAbi='armeabi-v7a', manufacturerName='samsung', brandName='samsung', modelName='SM-A015F'}
 VTL Version: 2.0 DEV, build: 08d5fb5

**Comment by ghosterfirst** [comment]
При нажатии «Готово».
Лог:
android.view.InflateException: Binary XML file line #8 in com.vtosters.lite:layout/picker_screen_avatar_area_selection: parent=FrameLayout:NO_ID, view=com.vk.attachpicker.widget.EditorBottomPanel:com.vtosters.lite:id/ebp_bottom
Caused by: android.view.InflateException: parent=FrameLayout:NO_ID, view=com.vk.attachpicker.widget.EditorBottomPanel:com.vtosters.lite:id/ebp_bottom
	at com.vk.core.ui.VKUILayoutFactory.onCreateView(VKUILayoutFactory.kt:40)
	at android.view.LayoutInflater.tryCreateView(LayoutInflater.java:1059)
	at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:995)
	at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:959)
	at android.view.LayoutInflater.rInflate(LayoutInflater.java:1121)
	at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:1082)
	at android.view.LayoutInflater.inflate(LayoutInflater.java:680)
	at android.view.LayoutInflater.inflate(LayoutInflater.java:532)
	at android.view.LayoutInflater.inflate(LayoutInflater.java:479)
	at com.vk.attachpicker.f.AvatarAreaSelectionScreen.a(AvatarAreaSelectionScreen.java:70)
	at com.vk.core.simplescreen.BaseScreen.b(BaseScreen.java:26)
	at com.vk.core.simplescreen.ScreenContainer.a(ScreenContainer.java:105)
	at com.vk.core.simplescreen.BaseScreen.a(BaseScreen.java:83)
	at com.vk.attachpicker.f.ViewerScreen$17.onClick(ViewerScreen.java:329)
	at android.view.View.performClick(View.java:8160)
	at android.view.View.performClickInternal(View.java:8137)
	at android.view.View.access$3700(View.java:888)
	at android.view.View$PerformClick.run(View.java:30236)
	at android.os.Handler.handleCallback(Handler.java:938)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:246)
	at android.app.ActivityThread.main(ActivityThread.java:8633)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:602)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1130)
Caused by: android.view.InflateException: Binary XML file line #8 in com.vtosters.lite:layout/picker_screen_avatar_area_selection: Error inflating class com.vk.attachpicker.widget.EditorBottomPanel
Caused by: java.lang.reflect.InvocationTargetException
	at java.lang.reflect.Constructor.newInstance0(Native Method)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:343)
	at android.view.LayoutInflater.createView(LayoutInflater.java:852)
	at android.view.LayoutInflater.createView(LayoutInflater.java:774)
	at com.vk.core.ui.VKLayoutInflater.a(VKLayoutInflater.kt:71)
	at com.vk.core.ui.VKUILayoutFactory.onCreateView(VKUILayoutFactory.kt:35)
	at android.view.LayoutInflater.tryCreateView(LayoutInflater.java:1059)
	at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:995)
	at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:959)
	at android.view.LayoutInflater.rInflate(LayoutInflater.java:1121)
	at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:1082)
	at android.view.LayoutInflater.inflate(LayoutInflater.java:680)
	at android.view.LayoutInflater.inflate(LayoutInflater.java:532)
	at android.view.LayoutInflater.inflate(LayoutInflater.java:479)
	at com.vk.attachpicker.f.AvatarAreaSelectionScreen.a(AvatarAreaSelectionScreen.java:70)
	at com.vk.core.simplescreen.BaseScreen.b(BaseScreen.java:26)
	at com.vk.core.simplescreen.ScreenContainer.a(ScreenContainer.java:105)
	at com.vk.core.simplescreen.BaseScreen.a(BaseScreen.java:83)
	at com.vk.attachpicker.f.ViewerScreen$17.onClick(ViewerScreen.java:329)
	at android.view.View.performClick(View.java:8160)
	at android.view.View.performClickInternal(View.java:8137)
	at android.view.View.access$3700(View.java:888)
	at android.view.View$PerformClick.run(View.java:30236)
	at android.os.Handler.handleCallback(Handler.java:938)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:246)
	at android.app.ActivityThread.main(ActivityThread.java:8633)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:602)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1130)
Caused by: android.view.InflateException: Binary XML file line #8 in com.vtosters.lite:layout/picker_layout_editor_bottom_panel: parent=EditorBottomPanel:com.vtosters.lite:id/ebp_bottom, view=ImageView:com.vtosters.lite:id/iv_apply
Caused by: android.view.InflateException: parent=EditorBottomPanel:com.vtosters.lite:id/ebp_bottom, view=ImageView:com.vtosters.lite:id/iv_apply
	at com.vk.core.ui.VKUILayoutFactory.onCreateView(VKUILayoutFactory.kt:40)
	at android.view.LayoutInflater.tryCreateView(LayoutInflater.java:1059)
	at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:995)
	at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:959)
	at android.view.LayoutInflater.rInflate(LayoutInflater.java:1121)
	at android.view.LayoutInflater.inflate(LayoutInflater.java:654)
	at android.view.LayoutInflater.inflate(LayoutInflater.java:532)
	at android.view.LayoutInflater.inflate(LayoutInflater.java:479)
	at com.vk.attachpicker.widget.EditorBottomPanel.a(EditorBottomPanel.java:47)
	at com.vk.attachpicker.widget.EditorBottomPanel.<init>(EditorBottomPanel.java:32)
	at java.lang.reflect.Constructor.newInstance0(Native Method)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:343)
	at android.view.LayoutInflater.createView(LayoutInflater.java:852)
	at android.view.LayoutInflater.createView(LayoutInflater.java:774)
	at com.vk.core.ui.VKLayoutInflater.a(VKLayoutInflater.kt:71)
	at com.vk.core.ui.VKUILayoutFactory.onCreateView(VKUILayoutFactory.kt:35)
	at android.view.LayoutInflater.tryCreateView(LayoutInflater.java:1059)
	at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:995)
	at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:959)
	at android.view.LayoutInflater.rInflate(LayoutInflater.java:1121)
	at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:1082)
	at android.view.LayoutInflater.inflate(LayoutInflater.java:680)
	at android.view.LayoutInflater.inflate(LayoutInflater.java:532)
	at android.view.LayoutInflater.inflate(LayoutInflater.java:479)
	at com.vk.attachpicker.f.AvatarAreaSelectionScreen.a(AvatarAreaSelectionScreen.java:70)
	at com.vk.core.simplescreen.BaseScreen.b(BaseScreen.java:26)
	at com.vk.core.simplescreen.ScreenContainer.a(ScreenContainer.java:105)
	at com.vk.core.simplescreen.BaseScreen.a(BaseScreen.java:83)
	at com.vk.attachpicker.f.ViewerScreen$17.onClick(ViewerScreen.java:329)
	at android.view.View.performClick(View.java:8160)
	at android.view.View.performClickInternal(View.java:8137)
	at android.view.View.access$3700(View.java:888)
	at android.view.View$PerformClick.run(View.java:30236)
	at android.os.Handler.handleCallback(Handler.java:938)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:246)
	at android.app.ActivityThread.main(ActivityThread.java:8633)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:602)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1130)
Caused by: java.lang.UnsupportedOperationException: Failed to resolve attribute at index 5: TypedValue{t=0x2/d=0x7f040022 a=-1}
	at android.content.res.TypedArray.getColorStateList(TypedArray.java:597)
	at android.widget.ImageView.<init>(ImageView.java:230)
	at android.widget.ImageView.<init>(ImageView.java:193)
	at android.support.v7.widget.AppCompatImageView.<init>(AppCompatImageView.java:71)
	at android.support.v7.widget.AppCompatImageView.<init>(AppCompatImageView.java:67)
	at android.support.v7.app.AppCompatViewInflater.b(AppCompatViewInflater.java:181)
	at android.support.v7.app.AppCompatViewInflater.a(AppCompatViewInflater.java:105)
	at android.support.v7.app.AppCompatDelegateImplV9.a(AppCompatDelegateImplV9.java:1035)
	at com.vk.core.ui.VKUILayoutFactory.onCreateView(VKUILayoutFactory.kt:32)
	... 39 more


Device{sdkVersion=30, productName='a01qser', deviceName='a01q', boardName='QC_Reference_Phone', cpuAbi='armeabi-v7a', manufacturerName='samsung', brandName='samsung', modelName='SM-A015F'}
 VTL Version: 2.0 DEV, build: 08d5fb5

**Comment by ghosterfirst** [comment]
При нажатии на «Все фото».
Лог:
android.view.InflateException: Binary XML file line #7 in com.vtosters.lite:layout/picker_adapter_album_spinner: parent=LinearLayout:NO_ID, view=TextView:com.vtosters.lite:id/tv_title
Caused by: android.view.InflateException: parent=LinearLayout:NO_ID, view=TextView:com.vtosters.lite:id/tv_title
	at com.vk.core.ui.VKUILayoutFactory.onCreateView(VKUILayoutFactory.kt:40)
	at android.view.LayoutInflater.tryCreateView(LayoutInflater.java:1059)
	at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:995)
	at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:959)
	at android.view.LayoutInflater.rInflate(LayoutInflater.java:1121)
	at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:1082)
	at android.view.LayoutInflater.rInflate(LayoutInflater.java:1124)
	at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:1082)
	at android.view.LayoutInflater.inflate(LayoutInflater.java:680)
	at android.view.LayoutInflater.inflate(LayoutInflater.java:532)
	at android.view.LayoutInflater.inflate(LayoutInflater.java:479)
	at com.vk.attachpicker.adapter.AlbumPickSpinnerAdapter$a.a(AlbumPickSpinnerAdapter.java:144)
	at com.vk.attachpicker.widget.ViewHolder.a(ViewHolder.java:28)
	at com.vk.attachpicker.adapter.AlbumPickSpinnerAdapter.getDropDownView(AlbumPickSpinnerAdapter.java:79)
	at android.widget.Spinner$DropDownAdapter.getDropDownView(Spinner.java:1116)
	at android.widget.Spinner$DropDownAdapter.getView(Spinner.java:1112)
	at android.widget.AbsListView.obtainView(AbsListView.java:2629)
	at android.widget.DropDownListView.obtainView(DropDownListView.java:335)
	at android.widget.ListView.measureHeightOfChildren(ListView.java:1452)
	at android.widget.ListPopupWindow.buildDropDown(ListPopupWindow.java:1358)
	at android.widget.ListPopupWindow.show(ListPopupWindow.java:681)
	at android.widget.Spinner$DropdownPopup.show(Spinner.java:1404)
	at android.widget.Spinner.performClick(Spinner.java:842)
	at android.support.v7.widget.AppCompatSpinner.performClick(AppCompatSpinner.java:442)
	at android.view.View.performClickInternal(View.java:8137)
	at android.view.View.access$3700(View.java:888)
	at android.view.View$PerformClick.run(View.java:30236)
	at android.os.Handler.handleCallback(Handler.java:938)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:246)
	at android.app.ActivityThread.main(ActivityThread.java:8633)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:602)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1130)
Caused by: java.lang.UnsupportedOperationException: Failed to resolve attribute at index 5: TypedValue{t=0x2/d=0x7f0404d0 a=-1}
	at android.content.res.TypedArray.getColorStateList(TypedArray.java:597)
	at android.widget.TextView.readTextAppearance(TextView.java:4326)
	at android.widget.TextView.<init>(TextView.java:1360)
	at android.widget.TextView.<init>(TextView.java:1241)
	at android.support.v7.widget.AppCompatTextView.<init>(AppCompatTextView.java:76)
	at com.vk.core.view.TextViewColorStateListAndAlphaSupportPreV23.<init>(TextViewColorStateListAndAlphaSupportPreV23.kt:12)
	at com.vk.core.view.TextViewColorStateListAndAlphaSupportPreV23.<init>(TextViewColorStateListAndAlphaSupportPreV23.kt:11)
	at com.vk.core.ui.VKUILayoutFactory.onCreateView(VKUILayoutFactory.kt:31)
	... 33 more


Device{sdkVersion=30, productName='a01qser', deviceName='a01q', boardName='QC_Reference_Phone', cpuAbi='armeabi-v7a', manufacturerName='samsung', brandName='samsung', modelName='SM-A015F'}
 VTL Version: 2.0 DEV, build: 08d5fb5

**Comment by gdlbo** [comment]
https://github.com/vtosters/lite/commit/0de0add85866255160ffa05a43f02f2344c261b0 fixed
