### ISSUE TITLE
Не работает редактор аватарки,не меняется аватар

### ISSUE THREAD

**Issue by roomijkee** [vtosters/lite#221]
java.lang.RuntimeException: Unable to start activity ComponentInfo{com.vtosters.lite/com.vk.attachpicker.PhotoVideoAttachActivity}: android.view.InflateException: Binary XML file line #2 in com.vtosters.lite:layout/picker_activity_photo_video_attach: parent=ContentFrameLayout:android:id/content, view=com.vk.attachpicker.widget.TopShadowLinearLayout:NO_ID
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3707)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3864)
	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:103)
	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2253)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loopOnce(Looper.java:201)
	at android.os.Looper.loop(Looper.java:288)
	at android.app.ActivityThread.main(ActivityThread.java:7870)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:550)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1003)
Caused by: android.view.InflateException: Binary XML file line #2 in com.vtosters.lite:layout/picker_activity_photo_video_attach: parent=ContentFrameLayout:android:id/content, view=com.vk.attachpicker.widget.TopShadowLinearLayout:NO_ID
Caused by: android.view.InflateException: parent=ContentFrameLayout:android:id/content, view=com.vk.attachpicker.widget.TopShadowLinearLayout:NO_ID
	at com.vk.core.ui.VKUILayoutFactory.onCreateView(VKUILayoutFactory.kt:40)
	at android.view.LayoutInflater.tryCreateView(LayoutInflater.java:1073)
	at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:1009)
	at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:973)
	at android.view.LayoutInflater.inflate(LayoutInflater.java:663)
	at android.view.LayoutInflater.inflate(LayoutInflater.java:538)
	at android.view.LayoutInflater.inflate(LayoutInflater.java:485)
	at android.support.v7.app.AppCompatDelegateImplV9.b(AppCompatDelegateImplV9.java:287)
	at android.support.v7.app.AppCompatActivity.setContentView(AppCompatActivity.java:139)
	at com.vk.attachpicker.PhotoVideoAttachActivity.onCreate(PhotoVideoAttachActivity.java:97)
	at android.app.Activity.performCreate(Activity.java:8054)
	at android.app.Activity.performCreate(Activity.java:8034)
	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1347)
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3688)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3864)
	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:103)
	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2253)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loopOnce(Looper.java:201)
	at android.os.Looper.loop(Looper.java:288)
	at android.app.ActivityThread.main(ActivityThread.java:7870)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:550)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1003)
Caused by: android.view.InflateException: Binary XML file line #2 in com.vtosters.lite:layout/picker_activity_photo_video_attach: Error inflating class com.vk.attachpicker.widget.TopShadowLinearLayout
Caused by: java.lang.reflect.InvocationTargetException
	at java.lang.reflect.Constructor.newInstance0(Native Method)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:343)
	at android.view.LayoutInflater.createView(LayoutInflater.java:863)
	at android.view.LayoutInflater.createView(LayoutInflater.java:780)
	at com.vk.core.ui.VKLayoutInflater.a(VKLayoutInflater.kt:71)
	at com.vk.core.ui.VKUILayoutFactory.onCreateView(VKUILayoutFactory.kt:35)
	at android.view.LayoutInflater.tryCreateView(LayoutInflater.java:1073)
	at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:1009)
	at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:973)
	at android.view.LayoutInflater.inflate(LayoutInflater.java:663)
	at android.view.LayoutInflater.inflate(LayoutInflater.java:538)
	at android.view.LayoutInflater.inflate(LayoutInflater.java:485)
	at android.support.v7.app.AppCompatDelegateImplV9.b(AppCompatDelegateImplV9.java:287)
	at android.support.v7.app.AppCompatActivity.setContentView(AppCompatActivity.java:139)
	at com.vk.attachpicker.PhotoVideoAttachActivity.onCreate(PhotoVideoAttachActivity.java:97)
	at android.app.Activity.performCreate(Activity.java:8054)
	at android.app.Activity.performCreate(Activity.java:8034)
	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1347)
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3688)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3864)
	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:103)
	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2253)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loopOnce(Looper.java:201)
	at android.os.Looper.loop(Looper.java:288)
	at android.app.ActivityThread.main(ActivityThread.java:7870)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:550)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1003)
Caused by: java.lang.UnsupportedOperationException: Failed to resolve attribute at index 13: TypedValue{t=0x2/d=0x7f0404b0 a=-1}
	at android.content.res.TypedArray.getDrawableForDensity(TypedArray.java:998)
	at android.content.res.TypedArray.getDrawable(TypedArray.java:982)
	at android.view.View.<init>(View.java:5534)
	at android.view.ViewGroup.<init>(ViewGroup.java:702)
	at android.widget.LinearLayout.<init>(LinearLayout.java:254)
	at android.widget.LinearLayout.<init>(LinearLayout.java:250)
	at android.widget.LinearLayout.<init>(LinearLayout.java:246)
	at com.vk.attachpicker.widget.TopShadowLinearLayout.<init>(TopShadowLinearLayout.java:24)
	... 31 more

Device{sdkVersion=32, productName='willow', deviceName='willow', boardName='trinket', cpuAbi='armeabi-v7a', manufacturerName='Xiaomi', brandName='Xiaomi', modelName='Redmi Note 8T'}
 VTL Version: 2.0 Beta, build: a9744bb

**Comment by gdlbo** [comment]
Обновись
