### ISSUE TITLE
Краш SuggestionsActivity

### ISSUE THREAD

**Issue by master-off** [vtosters/lite#230]
java.lang.VerifyError: Rejecting class com.vtosters.lite.SuggestionsActivity that attempts to sub-type erroneous class com.vtosters.lite.VKFragmentActivity (declaration of 'com.vtosters.lite.SuggestionsActivity' appears in /data/app/~~XgF2itxelIt-wSieAUynqw==/com.vtosters.lite-znFRF-G9EQvTEvTKHtzZXQ==/base.apk!classes2.dex)
	at java.lang.Class.newInstance(Native Method)
	at android.app.AppComponentFactory.instantiateActivity(AppComponentFactory.java:95)
	at android.app.Instrumentation.newActivity(Instrumentation.java:1273)
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3652)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3929)
	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:103)
	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2282)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loopOnce(Looper.java:210)
	at android.os.Looper.loop(Looper.java:299)
	at android.app.ActivityThread.main(ActivityThread.java:8250)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:556)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1045)
Caused by: java.lang.VerifyError: Verifier rejected class com.vtosters.lite.VKFragmentActivity: void com.vtosters.lite.VKFragmentActivity.onCreate(android.os.Bundle) failed to verify: void com.vtosters.lite.VKFragmentActivity.onCreate(android.os.Bundle): [0x13] Rejecting invocation, expected 1 argument registers, method signature has 2 or more (declaration of 'com.vtosters.lite.VKFragmentActivity' appears in /data/app/~~XgF2itxelIt-wSieAUynqw==/com.vtosters.lite-znFRF-G9EQvTEvTKHtzZXQ==/base.apk)
	... 16 more

Device{sdkVersion=31, productName='vayu_ru', deviceName='vayu', boardName='vayu', cpuAbi='armeabi-v7a', manufacturerName='Xiaomi', brandName='POCO', modelName='M2102J20SG'}
 VTL Version: Beta, build: e07d253

**Comment by gdlbo** [comment]
А очистка данных приложения помогала?
