### ISSUE TITLE
Вылет через каждые 10 минут.

### ISSUE THREAD

**Issue by ghosterfirst** [vtosters/lite#26]
Сижу, пишу, переключаюсь между диалогами и вылет через 10 минут.

**Comment by ghosterfirst** [comment]
Лог:
java.lang.NoClassDefFoundError: com.airbnb.lottie.a.b.ScaleKeyframeAnimation
	at com.airbnb.lottie.model.a.AnimatableScaleValue.a(AnimatableScaleValue.java:25)
	at com.airbnb.lottie.a.b.TransformKeyframeAnimation.<init>(TransformKeyframeAnimation.java:36)
	at com.airbnb.lottie.model.a.AnimatableTransform.h(AnimatableTransform.java:78)
	at com.airbnb.lottie.model.layer.BaseLayer.<init>(BaseLayer.java:102)
	at com.airbnb.lottie.model.layer.CompositionLayer.<init>(CompositionLayer.java:34)
	at com.airbnb.lottie.LottieDrawable.w(LottieDrawable.java:243)
	at com.airbnb.lottie.LottieDrawable.a(LottieDrawable.java:205)
	at com.airbnb.lottie.LottieAnimationView.setComposition(LottieAnimationView.java:493)
	at com.vk.stickers.views.animation.VKAnimationView$a.a(VKAnimationView.kt:61)
	at com.vk.stickers.views.animation.VKAnimationView$a.a(VKAnimationView.kt:15)
	at io.reactivex.internal.observers.LambdaObserver.b_(LambdaObserver.java:63)
	at io.reactivex.internal.operators.observable.ObservableScalarXMap$ScalarDisposable.run(ObservableScalarXMap.java:248)
	at io.reactivex.internal.operators.observable.ObservableJust.a_(ObservableJust.java:35)
	at io.reactivex.Observable.a(Observable.java:12030)
	at io.reactivex.Observable.a(Observable.java:12016)
	at io.reactivex.Observable.a(Observable.java:11945)
	at com.vk.stickers.views.animation.VKAnimationView.a(VKAnimationView.kt:58)
	at com.vk.stickers.AutoSuggestStickersPopupWindow$a$a.a(AutoSuggestStickersPopupWindow.java:525)
	at com.vk.stickers.AutoSuggestStickersPopupWindow$a.a(AutoSuggestStickersPopupWindow.java:423)
	at com.vk.stickers.AutoSuggestStickersPopupWindow$a.a(AutoSuggestStickersPopupWindow.java:349)
	at android.support.v7.widget.RecyclerView$a.a(RecyclerView.java:6673)
	at android.support.v7.widget.RecyclerView$a.b(RecyclerView.java:6714)
	at android.support.v7.widget.RecyclerView$p.a(RecyclerView.java:5647)
	at android.support.v7.widget.RecyclerView$p.a(RecyclerView.java:5913)
	at android.support.v7.widget.RecyclerView$p.a(RecyclerView.java:5752)
	at android.support.v7.widget.RecyclerView$p.c(RecyclerView.java:5748)
	at android.support.v7.widget.LinearLayoutManager$c.a(LinearLayoutManager.java:2232)
	at android.support.v7.widget.LinearLayoutManager.a(LinearLayoutManager.java:1559)
	at android.support.v7.widget.LinearLayoutManager.a(LinearLayoutManager.java:1519)
	at android.support.v7.widget.LinearLayoutManager.c(LinearLayoutManager.java:614)
	at android.support.v7.widget.RecyclerView.O(RecyclerView.java:3812)
	at android.support.v7.widget.RecyclerView.onMeasure(RecyclerView.java:3225)
	at android.view.View.measure(View.java:27131)
	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:7951)
	at android.widget.FrameLayout.onMeasure(FrameLayout.java:194)
	at com.vk.stickers.LeftDeltaLayout.onMeasure(LeftDeltaLayout.java:62)
	at android.view.View.measure(View.java:27131)
	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:7951)
	at android.widget.FrameLayout.onMeasure(FrameLayout.java:194)
	at android.view.View.measure(View.java:27131)
	at android.view.ViewRootImpl.performMeasure(ViewRootImpl.java:4187)
	at android.view.ViewRootImpl.measureHierarchy(ViewRootImpl.java:2936)
	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:3204)
	at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:2618)
	at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:9971)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1010)
	at android.view.Choreographer.doCallbacks(Choreographer.java:809)
	at android.view.Choreographer.doFrame(Choreographer.java:744)
	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:995)
	at android.os.Handler.handleCallback(Handler.java:938)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:246)
	at android.app.ActivityThread.main(ActivityThread.java:8633)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:602)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1130)
Caused by: java.lang.VerifyError: Verifier rejected class com.airbnb.lottie.a.b.ScaleKeyframeAnimation: com.airbnb.lottie.e.ScaleXY com.airbnb.lottie.a.b.ScaleKeyframeAnimation.b(com.airbnb.lottie.e.Keyframe, float) failed to verify: com.airbnb.lottie.e.ScaleXY com.airbnb.lottie.a.b.ScaleKeyframeAnimation.b(com.airbnb.lottie.e.Keyframe, float): [0x4F] returning 'Reference: com.airbnb.lottie.e.Keyframe', but expected from declaration 'Reference: com.airbnb.lottie.e.ScaleXY' (declaration of 'com.airbnb.lottie.a.b.ScaleKeyframeAnimation' appears in base.apk!classes3.dex)
	at com.airbnb.lottie.model.a.AnimatableScaleValue.a(AnimatableScaleValue.java:25)
	at com.airbnb.lottie.a.b.TransformKeyframeAnimation.<init>(TransformKeyframeAnimation.java:36)
	at com.airbnb.lottie.model.a.AnimatableTransform.h(AnimatableTransform.java:78)
	at com.airbnb.lottie.model.layer.BaseLayer.<init>(BaseLayer.java:102)
	at com.airbnb.lottie.model.layer.CompositionLayer.<init>(CompositionLayer.java:34)
	at com.airbnb.lottie.LottieDrawable.w(LottieDrawable.java:243)
	at com.airbnb.lottie.LottieDrawable.a(LottieDrawable.java:205)
	at com.airbnb.lottie.LottieAnimationView.setComposition(LottieAnimationView.java:493)
	at com.vk.stickers.views.animation.VKAnimationView$a.a(VKAnimationView.kt:61)
	at com.vk.stickers.views.animation.VKAnimationView$a.a(VKAnimationView.kt:15)
	at io.reactivex.internal.observers.LambdaObserver.b_(LambdaObserver.java:63)
	at io.reactivex.internal.operators.observable.ObservableDoOnEach$a.b_(ObservableDoOnEach.java:103)
	at io.reactivex.internal.operators.observable.ObservableObserveOn$ObserveOnObserver.g(ObservableObserveOn.java:200)
	at io.reactivex.internal.operators.observable.ObservableObserveOn$ObserveOnObserver.run(ObservableObserveOn.java:252)
	at io.reactivex.schedulers.HandlerScheduler$b.run(HandlerScheduler.java:119)
	... 7 more


Device{sdkVersion=30, productName='a01qser', deviceName='a01q', boardName='QC_Reference_Phone', cpuAbi='armeabi-v7a', manufacturerName='samsung', brandName='samsung', modelName='SM-A015F'}
 VTL Version: 2.0 DEV, build: 81294ac

**Comment by gdlbo** [comment]
https://github.com/vtosters/lite/issues/5
