### ISSUE TITLE
Ошибка при открытии поста из группы ВК через шторку уведомлений на Андроиде 

### ISSUE THREAD

**Issue by IGOR3K99** [vtosters/lite#28]
time: 1648305849913
msg: java.lang.UnsupportedOperationException: Failed to resolve attribute at index 6: TypedValue{t=0x2/d=0x101009b a=1}
stacktrace: android.view.InflateException: Binary XML file line #41: Binary XML file line #41: Error inflating class android.widget.TextView
Caused by: android.view.InflateException: Binary XML file line #41: Error inflating class android.widget.TextView
Caused by: java.lang.reflect.InvocationTargetException
	at java.lang.reflect.Constructor.newInstance0(Native Method)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:343)
	at android.view.LayoutInflater.createView(LayoutInflater.java:647)
	at com.android.internal.policy.PhoneLayoutInflater.onCreateView(PhoneLayoutInflater.java:58)
	at android.view.LayoutInflater.onCreateView(LayoutInflater.java:720)
	at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:788)
	at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:730)
	at android.view.LayoutInflater.rInflate(LayoutInflater.java:863)
	at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:824)
	at android.view.LayoutInflater.rInflate(LayoutInflater.java:866)
	at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:824)
	at android.view.LayoutInflater.inflate(LayoutInflater.java:515)
	at android.view.LayoutInflater.inflate(LayoutInflater.java:423)
	at android.view.LayoutInflater.inflate(LayoutInflater.java:374)
	at android.app.ProgressDialog.onCreate(ProgressDialog.java:233)
	at android.app.Dialog.dispatchOnCreate(Dialog.java:407)
	at android.app.Dialog.show(Dialog.java:302)
	at com.vk.core.extensions.RxExt1.b(RxExt.kt:124)
	at com.vk.core.extensions.RxExt1.b(RxExt.kt:77)
	at com.vk.core.extensions.RxExt$d.run(RxExt.kt:104)
	at android.os.Handler.handleCallback(Handler.java:873)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:193)
	at android.app.ActivityThread.main(ActivityThread.java:6672)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:495)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:860)
Caused by: java.lang.UnsupportedOperationException: Failed to resolve attribute at index 6: TypedValue{t=0x2/d=0x101009b a=1}
	at android.content.res.TypedArray.getColorStateList(TypedArray.java:546)
	at android.widget.TextView.readTextAppearance(TextView.java:3565)
	at android.widget.TextView.<init>(TextView.java:941)
	at android.widget.TextView.<init>(TextView.java:886)
	at android.widget.TextView.<init>(TextView.java:882)
	... 27 more

**Comment by gdlbo** [comment]
Нужны более подробные логи данной проблемы

**Comment by IGOR3K99** [comment]
> Нужны более подробные логи данной проблемы

К сожалению более подробные логи предоставить я не могу. Так как это всё, что мне вот эта встроенная андроидовская фигня смогла показать.
