### ISSUE TITLE
Вылет при попытке зайти в настройку музыки

### ISSUE THREAD

**Issue by Kreative2017** [vtosters/lite#338]
java.lang.RuntimeException: Unable to start activity ComponentInfo{com.vtosters.lite/com.vtosters.lite.FragmentWrapperActivity}: java.lang.NullPointerException: Attempt to invoke virtual method 'void android.support.v7.preference.Preference.a(android.support.v7.preference.Preference$c)' on a null object reference
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3494)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3666)
	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:85)
	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2112)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loop(Looper.java:236)
	at android.app.ActivityThread.main(ActivityThread.java:7889)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:600)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:967)
Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'void android.support.v7.preference.Preference.a(android.support.v7.preference.Preference$c)' on a null object reference
	at ru.vtosters.lite.ui.fragments.MusicFragment.prefs(MusicFragment.java:24)
	at ru.vtosters.lite.ui.fragments.MusicFragment.b(MusicFragment.java:20)
	at android.support.v4.app.Fragment.l(Fragment.java:2331)
	at android.support.v4.app.FragmentManager1.a(FragmentManager.java:1386)
	at android.support.v4.app.FragmentTransition.a(FragmentTransition.java:1188)
	at android.support.v4.app.FragmentTransition.a(FragmentTransition.java:1071)
	at android.support.v4.app.FragmentTransition.a(FragmentTransition.java:115)
	at android.support.v4.app.FragmentManager1.a(FragmentManager.java:2380)
	at android.support.v4.app.FragmentManager1.b(FragmentManager.java:2338)
	at android.support.v4.app.FragmentManager1.b(FragmentManager.java:2215)
	at android.support.v4.app.BackStackRecord.e(BackStackRecord.java:649)
	at com.vk.core.fragments.b.a.ParentSupportFragmentManager.g(ParentSupportFragmentManager.kt:83)
	at com.vk.core.fragments.FragmentNavigationController.a(FragmentNavigationController.kt:271)
	at com.vk.core.fragments.FragmentNavigationController.a(FragmentNavigationController.kt:15)
	at com.vk.core.fragments.FragmentNavigationController$show$1.b(FragmentNavigationController.kt:89)
	at com.vk.core.fragments.FragmentNavigationController$show$1.E_(FragmentNavigationController.kt:15)
	at com.vk.core.fragments.FragmentNavigationController.a(FragmentNavigationController.kt:307)
	at com.vk.core.fragments.FragmentNavigationController.a(FragmentNavigationController.kt:83)
	at com.vk.navigation.NavigationDelegateBottom$f.run(NavigationDelegateBottom.kt:569)
	at com.vk.core.util.ThreadUtils.b(ThreadUtils.kt:60)
	at com.vk.core.util.ThreadUtils.b(ThreadUtils.kt:58)
	at com.vk.navigation.NavigationDelegateBottom.a(NavigationDelegateBottom.kt:565)
	at com.vtosters.lite.FragmentWrapperActivity.onCreate(FragmentWrapperActivity.java:91)
	at android.app.Activity.performCreate(Activity.java:8109)
	at android.app.Activity.performCreate(Activity.java:8083)
	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1310)
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3467)
	... 11 more

Device{sdkVersion=30, productName='surya_eea', deviceName='surya', boardName='surya', cpuAbi='armeabi-v7a', manufacturerName='Xiaomi', brandName='POCO', modelName='M2007J20CG'}, commit: e389f7d

**Comment by aliveoutside** [comment]
#327
