### ISSUE TITLE
Вылет при входе в секцию комментариев 

### ISSUE THREAD

**Issue by BetaHe1per** [vtosters/lite#520]
Стабильный вылет при входе в секцию комментариев через сегмент уведомлений. 
Также иногда не отображает список комментариев к посту после отправки комментария. 

Копирую лог вылета:
java.lang.VerifyError: Verifier rejected class com.vtosters.lite.api.newsfeed.NewsfeedGetComments: com.vk.dto.common.data.VKFromList com.vtosters.lite.api.newsfeed.NewsfeedGetComments.a(org.json.JSONObject) failed to verify: com.vk.dto.common.data.VKFromList com.vtosters.lite.api.newsfeed.NewsfeedGetComments.a(org.json.JSONObject): [0x69] register v4 has type Precise Reference: com.vk.dto.newsfeed.Owner but expected Reference: org.json.JSONObject (declaration of 'com.vtosters.lite.api.newsfeed.NewsfeedGetComments' appears in base.apk!classes4.dex)
	at com.vk.newsfeed.presenters.CommentsPostListPresenter.a(CommentsPostListPresenter.kt:7)
	at com.vk.newsfeed.presenters.CommentsPostListPresenter.a(CommentsPostListPresenter.kt:2)
	at com.vk.lists.PaginationHelper.a(PaginationHelper.java:33)
	at com.vk.lists.PaginationHelper.h(PaginationHelper.java:2)
	at com.vk.lists.PaginationHelper.a(PaginationHelper.java:13)
	at com.vk.lists.PaginationHelper$k.a(PaginationHelper.java:9)
	at com.vk.lists.PaginationHelperExt.b(PaginationHelperExt.kt:2)
	at com.vk.newsfeed.EntriesListFragment.a(EntriesListFragment.kt:5)
	at com.vk.newsfeed.presenters.CommentsPostListPresenter.x(CommentsPostListPresenter.kt:5)
	at com.vk.newsfeed.presenters.EntriesListPresenter.b(EntriesListPresenter.kt:9)
	at com.vk.newsfeed.EntriesListFragment.onViewCreated(EntriesListFragment.kt:26)
	at com.vtosters.lite.fragments.q2.CommentsPostListFragment.onViewCreated(CommentsPostListFragment.java:1)
	at androidx.fragment.app.FragmentManagerImpl.moveToState(FragmentManager.java:72)
	at androidx.fragment.app.FragmentManagerImpl.moveFragmentToExpectedState(FragmentManager.java:6)
	at androidx.fragment.app.FragmentManagerImpl.moveToState(FragmentManager.java:150)
	at androidx.fragment.app.BackStackRecord.executeOps(BackStackRecord.java:24)
	at androidx.fragment.app.FragmentManagerImpl.executeOps(FragmentManager.java:6)
	at androidx.fragment.app.FragmentManagerImpl.executeOpsTogether(FragmentManager.java:14)
	at androidx.fragment.app.FragmentManagerImpl.removeRedundantOperationsAndExecute(FragmentManager.java:10)
	at androidx.fragment.app.FragmentManagerImpl.execSingleAction(FragmentManager.java:5)
	at androidx.fragment.app.BackStackRecord.commitNowAllowingStateLoss(BackStackRecord.java:2)
	at com.vk.core.fragments.j.b.ParentSupportFragmentManager.c(ParentSupportFragmentManager.kt:1)
	at com.vk.core.fragments.FragmentManagerImplSimple.b(FragmentManagerImplSimple.kt:3)
	at com.vk.notifications.NotificationsContainerFragment.P4(NotificationsContainerFragment.kt:3)
	at com.vk.notifications.NotificationsFragment$onCreateView$$inlined$let$lambda$1.a(NotificationsFragment.kt:7)
	at com.vk.notifications.NotificationsFragment$onCreateView$$inlined$let$lambda$1.invoke(NotificationsFragment.kt:1)
	at com.vk.newsfeed.NotificationsListAdapter$ItemViewHolder$1.a(NotificationsListAdapter.kt:3)
	at com.vk.newsfeed.NotificationsListAdapter$ItemViewHolder$1.invoke(NotificationsListAdapter.kt:1)
	at com.vk.extensions.ViewExtKt$q.onClick(ViewExt.kt:1)
	at android.view.View.performClick(View.java:7753)
	at android.view.View.performClickInternal(View.java:7730)
	at android.view.View.access$3700(View.java:861)
	at android.view.View$PerformClick.run(View.java:29136)
	at android.os.Handler.handleCallback(Handler.java:938)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:210)
	at android.os.Looper.loop(Looper.java:299)
	at android.app.ActivityThread.main(ActivityThread.java:8105)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:556)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1045)

**Comment by gdlbo** [comment]
https://github.com/vtosters/lite/commit/3aaca80da17f3cf3c533ac62d664455194933456
