### ISSUE TITLE
Втостерслайт вылетает 

### ISSUE THREAD

**Issue by Kingglionn2** [vtosters/lite#623]
**Опишите сам баг**
При обновлении новостей вылезает ошибка

**Опишите действия для воспроизведения ошибки**
1. Обновил ленту интересных новостей
2. Пролистал до конца страницы

**Опишите ожидаемый результат**
Интересная лента должна прогружать результаты

**Скриншот ошибки**

**Информация об устройстве:**
 - Устройство: Samsung Galaxy J1 Mini
 - OS: Android 9 | OneUi 3.0
 - Коммит: fa12e8f (В О Приложении написана версия коммита)

**Дополнительная информация о баге или мыслях почему оно может происходить (если есть)**

**Comment by k1zn** [comment]
какая версия приложения? (не пиши "последняя")

**Comment by Kingglionn2** [comment]
0.46
--
Отправлено из Mail.ru для Android вторник, 16 августа 2022г., 01:11 +05:00 от k1zn  ***@***.*** :

**Comment by aliveoutside** [comment]
не могу воспроизвести
нужны логи после вылета

**Comment by Kingglionn2** [comment]
--
Отправлено из Mail.ru для Android вторник, 16 августа 2022г., 06:29 +05:00 от aliveoutside  ***@***.*** :

>не могу воспроизвести
>нужны логи после вылета
>—
>Reply to this email directly,  view it on GitHub , or  unsubscribe .
>You are receiving this because you authored the thread. Message ID:  @ github . com>
java.lang.NullPointerException: Attempt to invoke virtual method 'int com.vk.im.engine.models.dialogs.Dialog.getId()' on a null object reference
	at ru.vtosters.lite.dnr.DNRInjector.injectToListAccess(DNRInjector.java:115)
	at com.vk.im.ui.components.dialog_header.info.DialogHeaderInfoComponent.X(DialogHeaderInfoComponent.kt:1)
	at com.vk.im.ui.components.dialog_header.info.DialogHeaderInfoComponent.d0(DialogHeaderInfoComponent.kt:1)
	at com.vk.im.ui.components.dialog_header.info.DialogHeaderInfoComponent.a0(DialogHeaderInfoComponent.kt:5)
	at com.vk.im.ui.components.dialog_header.info.DialogHeaderInfoComponent.i0(DialogHeaderInfoComponent.kt:15)
	at com.vk.im.ui.components.dialog_header.info.DialogHeaderInfoComponent.a(DialogHeaderInfoComponent.kt:14)
	at com.vk.im.ui.components.dialog_header.info.DialogHeaderInfoComponent.a(DialogHeaderInfoComponent.kt:12)
	at com.vk.im.ui.components.dialog_header.DialogHeaderController.a(DialogHeaderController.kt:15)
	at com.vk.im.ui.fragments.ChatFragment.b(ChatFragment.kt:21)
	at com.vk.navigation.NavigationDelegate.a(NavigationDelegate.kt:20)
	at com.vk.navigation.NavigationDelegate$show$applyNewIntent$1.a(NavigationDelegate.kt:1)
	at com.vk.navigation.NavigationDelegate$show$applyNewIntent$1.invoke(NavigationDelegate.kt:1)
	at com.vk.core.fragments.FragmentNavigationController$showAndReorder$1.invoke(FragmentNavigationController.kt:15)
	at com.vk.core.fragments.FragmentNavigationController$showAndReorder$1.invoke(FragmentNavigationController.kt:1)
	at com.vk.core.fragments.FragmentNavigationController.a(FragmentNavigationController.kt:77)
	at com.vk.core.fragments.FragmentNavigationController.a(FragmentNavigationController.kt:17)
	at com.vk.navigation.NavigationDelegate.a(NavigationDelegate.kt:18)
	at com.vk.navigation.NavigationDelegateBottom$g.run(NavigationDelegateBottom.kt:1)
	at com.vk.core.util.ThreadUtils.b(ThreadUtils.kt:5)
	at com.vk.core.util.ThreadUtils.e(ThreadUtils.kt:1)
	at com.vk.navigation.NavigationDelegateBottom.a(NavigationDelegateBottom.kt:83)
	at com.vk.navigation.NavigationDelegateBottom.d(NavigationDelegateBottom.kt:12)
	at com.vk.navigation.NavigationDelegateActivity.onNewIntent(NavigationDelegateActivity.kt:2)
	at com.vtosters.lite.MainActivity.onNewIntent(MainActivity.java:1)
	at android.app.Activity.performNewIntent(Activity.java:8222)
	at android.app.Instrumentation.callActivityOnNewIntent(Instrumentation.java:1409)
	at android.app.Instrumentation.callActivityOnNewIntent(Instrumentation.java:1422)
	at android.app.ActivityThread.deliverNewIntents(ActivityThread.java:4085)
	at android.app.ActivityThread.handleNewIntent(ActivityThread.java:4097)
	at android.app.servertransaction.NewIntentItem.execute(NewIntentItem.java:53)
	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2336)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loop(Looper.java:246)
	at android.app.ActivityThread.main(ActivityThread.java:8653)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:602)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1130)


Device{sdkVersion=30, productName='a12nsser', deviceName='a12', boardName='k65v1_64_bsp_titan_rat', cpuAbi='armeabi-v7a', manufacturerName='samsung', brandName='samsung', modelName='SM-A125F'}, commit: 2a58d72

**Comment by gdlbo** [comment]
https://github.com/vtosters/lite/commit/44c844524d49e467b3e0b18eb9ff3388134d8992 исправлено
