### ISSUE TITLE
Краш при установке авы.

### ISSUE THREAD

**Issue by vloneheck** [vtosters/lite#70]
Лог: android.view.InflateException: Binary XML file line #8 in com.vtosters.lite:layout/picker_screen_avatar_area_selection: parent=FrameLayout:NO_ID, view=com.vk.attachpicker.widget.EditorBottomPanel:com.vtosters.lite:id/ebp_bottom
Caused by: android.view.InflateException: parent=FrameLayout:NO_ID, view=com.vk.attachpicker.widget.EditorBottomPanel:com.vtosters.lite:id/ebp_bottom
	at com.vk.core.ui.VKUILayoutFactory.onCreateView(VKUILayoutFactory.kt:40)
	at android.view.LayoutInflater.tryCreateView(LayoutInflater.java:1063)
	at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:999)
	at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:963)
	at android.view.LayoutInflater.rInflate(LayoutInflater.java:1125)
	at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:1086)
	at android.view.LayoutInflater.inflate(LayoutInflater.java:684)
	at android.view.LayoutInflater.inflate(LayoutInflater.java:536)
	at android.view.LayoutInflater.inflate(LayoutInflater.java:479)
	at com.vk.attachpicker.f.AvatarAreaSelectionScreen.a(AvatarAreaSelectionScreen.java:70)
	at com.vk.core.simplescreen.BaseScreen.b(BaseScreen.java:26)
	at com.vk.core.simplescreen.ScreenContainer.a(ScreenContainer.java:105)
	at com.vk.core.simplescreen.BaseScreen.a(BaseScreen.java:83)
	at com.vk.attachpicker.f.ViewerScreen$17.onClick(ViewerScreen.java:329)
	at android.view.View.performClick(View.java:7559)
	at android.view.View.performClickInternal(View.java:7536)
	at android.view.View.access$3600(View.java:828)
	at android.view.View$PerformClick.run(View.java:28700)
	at android.os.Handler.handleCallback(Handler.java:938)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:236)
	at android.app.ActivityThread.main(ActivityThread.java:7861)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:600)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:967)
Caused by: android.view.InflateException: Binary XML file line #8 in com.vtosters.lite:layout/picker_screen_avatar_area_selection: Error inflating class com.vk.attachpicker.widget.EditorBottomPanel
Caused by: java.lang.reflect.InvocationTargetException
	at java.lang.reflect.Constructor.newInstance0(Native Method)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:343)
	at android.view.LayoutInflater.createView(LayoutInflater.java:856)
	at android.view.LayoutInflater.createView(LayoutInflater.java:778)
	at com.vk.core.ui.VKLayoutInflater.a(VKLayoutInflater.kt:71)
	at com.vk.core.ui.VKUILayoutFactory.onCreateView(VKUILayoutFactory.kt:35)
	at android.view.LayoutInflater.tryCreateView(LayoutInflater.java:1063)
	at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:999)
	at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:963)
	at android.view.LayoutInflater.rInflate(LayoutInflater.java:1125)
	at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:1086)
	at android.view.LayoutInflater.inflate(LayoutInflater.java:684)
	at android.view.LayoutInflater.inflate(LayoutInflater.java:536)
	at android.view.LayoutInflater.inflate(LayoutInflater.java:479)
	at com.vk.attachpicker.f.AvatarAreaSelectionScreen.a(AvatarAreaSelectionScreen.java:70)
	at com.vk.core.simplescreen.BaseScreen.b(BaseScreen.java:26)
	at com.vk.core.simplescreen.ScreenContainer.a(ScreenContainer.java:105)
	at com.vk.core.simplescreen.BaseScreen.a(BaseScreen.java:83)
	at com.vk.attachpicker.f.ViewerScreen$17.onClick(ViewerScreen.java:329)
	at android.view.View.performClick(View.java:7559)
	at android.view.View.performClickInternal(View.java:7536)
	at android.view.View.access$3600(View.java:828)
	at android.view.View$PerformClick.run(View.java:28700)
	at android.os.Handler.handleCallback(Handler.java:938)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:236)
	at android.app.ActivityThread.main(ActivityThread.java:7861)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:600)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:967)
Caused by: android.view.InflateException: Binary XML file line #8 in com.vtosters.lite:layout/picker_layout_editor_bottom_panel: parent=EditorBottomPanel:com.vtosters.lite:id/ebp_bottom, view=ImageView:com.vtosters.lite:id/iv_apply
Caused by: android.view.InflateException: parent=EditorBottomPanel:com.vtosters.lite:id/ebp_bottom, view=ImageView:com.vtosters.lite:id/iv_apply
	at com.vk.core.ui.VKUILayoutFactory.onCreateView(VKUILayoutFactory.kt:40)
	at android.view.LayoutInflater.tryCreateView(LayoutInflater.java:1063)
	at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:999)
	at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:963)
	at android.view.LayoutInflater.rInflate(LayoutInflater.java:1125)
	at android.view.LayoutInflater.inflate(LayoutInflater.java:658)
	at android.view.LayoutInflater.inflate(LayoutInflater.java:536)
	at android.view.LayoutInflater.inflate(LayoutInflater.java:479)
	at com.vk.attachpicker.widget.EditorBottomPanel.a(EditorBottomPanel.java:47)
	at com.vk.attachpicker.widget.EditorBottomPanel.<init>(EditorBottomPanel.java:32)
	at java.lang.reflect.Constructor.newInstance0(Native Method)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:343)
	at android.view.LayoutInflater.createView(LayoutInflater.java:856)
	at android.view.LayoutInflater.createView(LayoutInflater.java:778)
	at com.vk.core.ui.VKLayoutInflater.a(VKLayoutInflater.kt:71)
	at com.vk.core.ui.VKUILayoutFactory.onCreateView(VKUILayoutFactory.kt:35)
	at android.view.LayoutInflater.tryCreateView(LayoutInflater.java:1063)
	at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:999)
	at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:963)
	at android.view.LayoutInflater.rInflate(LayoutInflater.java:1125)
	at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:1086)
	at android.view.LayoutInflater.inflate(LayoutInflater.java:684)
	at android.view.LayoutInflater.inflate(LayoutInflater.java:536)
	at android.view.LayoutInflater.inflate(LayoutInflater.java:479)
	at com.vk.attachpicker.f.AvatarAreaSelectionScreen.a(AvatarAreaSelectionScreen.java:70)
	at com.vk.core.simplescreen.BaseScreen.b(BaseScreen.java:26)
	at com.vk.core.simplescreen.ScreenContainer.a(ScreenContainer.java:105)
	at com.vk.core.simplescreen.BaseScreen.a(BaseScreen.java:83)
	at com.vk.attachpicker.f.ViewerScreen$17.onClick(ViewerScreen.java:329)
	at android.view.View.performClick(View.java:7559)
	at android.view.View.performClickInternal(View.java:7536)
	at android.view.View.access$3600(View.java:828)
	at android.view.View$PerformClick.run(View.java:28700)
	at android.os.Handler.handleCallback(Handler.java:938)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:236)
	at android.app.ActivityThread.main(ActivityThread.java:7861)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:600)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:967)
Caused by: java.lang.UnsupportedOperationException: Failed to resolve attribute at index 5: TypedValue{t=0x2/d=0x7f040022 a=-1}
	at android.content.res.TypedArray.getColorStateList(TypedArray.java:599)
	at android.widget.ImageView.<init>(ImageView.java:227)
	at android.widget.ImageView.<init>(ImageView.java:190)
	at android.support.v7.widget.AppCompatImageView.<init>(AppCompatImageView.java:71)
	at android.support.v7.widget.AppCompatImageView.<init>(AppCompatImageView.java:67)
	at android.support.v7.app.AppCompatViewInflater.b(AppCompatViewInflater.java:181)
	at android.support.v7.app.AppCompatViewInflater.a(AppCompatViewInflater.java:105)
	at android.support.v7.app.AppCompatDelegateImplV9.a(AppCompatDelegateImplV9.java:1035)
	at com.vk.core.ui.VKUILayoutFactory.onCreateView(VKUILayoutFactory.kt:32)
	... 39 more

Device{sdkVersion=30, productName='curtana_ru', deviceName='curtana', boardName='curtana', cpuAbi='armeabi-v7a', manufacturerName='Xiaomi', brandName='Redmi', modelName='Redmi Note 9S'}
 VTL Version: 2.0 DEV, build: 49a2526

**Comment by gdlbo** [comment]
https://github.com/vtosters/lite/commit/834d7e1da14a1667898420ede9efd329e870249b
