### ISSUE TITLE
Крашит в диалогах при попытке открыть предлагаемые стикеры 

### ISSUE THREAD

**Issue by SingularityLost** [vtosters/lite#71]
При написании сообщения "А я" вызывает всплывающее меню с предлагаемыми стикерами. Не успевает отобразиться даже один предлагаемый стикер, как происходит краш приложения. Баг воспроизводится на ура. Android 12. Лог из приложения ниже.

java.lang.IllegalStateException: Missing values for keyframe.
	at com.airbnb.lottie.a.b.FloatKeyframeAnimation.b(FloatKeyframeAnimation.java:16)
	at com.airbnb.lottie.a.b.FloatKeyframeAnimation.a(FloatKeyframeAnimation.java:8)
	at com.airbnb.lottie.a.b.BaseKeyframeAnimation.e(BaseKeyframeAnimation.java:125)
	at com.airbnb.lottie.a.b.TransformKeyframeAnimation.d(TransformKeyframeAnimation.java:113)
	at com.airbnb.lottie.model.layer.BaseLayer.a(BaseLayer.java:199)
	at com.airbnb.lottie.model.layer.CompositionLayer.b(CompositionLayer.java:100)
	at com.airbnb.lottie.model.layer.BaseLayer.a(BaseLayer.java:201)
	at com.airbnb.lottie.LottieDrawable.draw(LottieDrawable.java:319)
	at android.widget.ImageView.onDraw(ImageView.java:1442)
	at com.vk.stickers.views.animation.VKAnimationView.onDraw(VKAnimationView.kt:88)
	at android.view.View.draw(View.java:22658)
	at android.view.View.buildDrawingCacheImpl(View.java:21930)
	at android.view.View.buildDrawingCache(View.java:21790)
	at android.view.View.draw(View.java:22381)
	at android.view.ViewGroup.drawChild(ViewGroup.java:4528)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4289)
	at android.view.View.updateDisplayListIfDirty(View.java:21524)
	at android.view.View.draw(View.java:22389)
	at android.view.ViewGroup.drawChild(ViewGroup.java:4528)
	at android.support.v7.widget.RecyclerView.drawChild(RecyclerView.java:4703)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4289)
	at android.view.View.draw(View.java:22661)
	at android.support.v7.widget.RecyclerView.draw(RecyclerView.java:4107)
	at android.view.View.updateDisplayListIfDirty(View.java:21533)
	at android.view.View.draw(View.java:22389)
	at android.view.ViewGroup.drawChild(ViewGroup.java:4528)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4289)
	at android.view.View.updateDisplayListIfDirty(View.java:21524)
	at android.view.View.draw(View.java:22389)
	at android.view.ViewGroup.drawChild(ViewGroup.java:4528)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4289)
	at android.view.View.updateDisplayListIfDirty(View.java:21524)
	at android.view.ThreadedRenderer.updateViewTreeDisplayList(ThreadedRenderer.java:534)
	at android.view.ThreadedRenderer.updateRootDisplayList(ThreadedRenderer.java:540)
	at android.view.ThreadedRenderer.draw(ThreadedRenderer.java:616)
	at android.view.ViewRootImpl.draw(ViewRootImpl.java:4425)
	at android.view.ViewRootImpl.performDraw(ViewRootImpl.java:4153)
	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:3313)
	at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:2133)
	at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:8665)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1120)
	at android.view.Choreographer.doCallbacks(Choreographer.java:926)
	at android.view.Choreographer.doFrame(Choreographer.java:859)
	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1105)
	at android.os.Handler.handleCallback(Handler.java:938)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:346)
	at android.os.Looper.loop(Looper.java:475)
	at android.app.ActivityThread.main(ActivityThread.java:7889)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1009)

Device{sdkVersion=31, productName='XQ-BC72_RU', deviceName='XQ-BC72', boardName='lahaina', cpuAbi='armeabi-v7a', manufacturerName='Sony', brandName='Sony', modelName='XQ-BC72'}
 VTL Version: 2.0 DEV, build: 49a2526

**Comment by gdlbo** [comment]
https://github.com/vtosters/lite/issues/5
