### ISSUE TITLE
Краш при всплывающих стикерах

### ISSUE THREAD

**Issue by Perfezdo** [vtosters/lite#83]
java.lang.IllegalStateException: Missing values for keyframe.
	at com.airbnb.lottie.a.b.FloatKeyframeAnimation.b(FloatKeyframeAnimation.java:16)
	at com.airbnb.lottie.a.b.FloatKeyframeAnimation.a(FloatKeyframeAnimation.java:8)
	at com.airbnb.lottie.a.b.BaseKeyframeAnimation.e(BaseKeyframeAnimation.java:125)
	at com.airbnb.lottie.a.b.TransformKeyframeAnimation.d(TransformKeyframeAnimation.java:113)
	at com.airbnb.lottie.model.layer.BaseLayer.a(BaseLayer.java:199)
	at com.airbnb.lottie.model.layer.CompositionLayer.b(CompositionLayer.java:100)
	at com.airbnb.lottie.model.layer.BaseLayer.a(BaseLayer.java:201)
	at com.airbnb.lottie.LottieDrawable.draw(LottieDrawable.java:319)
	at android.widget.ImageView.onDraw(ImageView.java:1434)
	at com.vk.stickers.views.animation.VKAnimationView.onDraw(VKAnimationView.kt:88)
	at android.view.View.draw(View.java:21547)
	at android.view.View.buildDrawingCacheImpl(View.java:20818)
	at android.view.View.buildDrawingCache(View.java:20678)
	at android.view.View.draw(View.java:21268)
	at android.view.ViewGroup.drawChild(ViewGroup.java:4417)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4177)
	at android.view.View.updateDisplayListIfDirty(View.java:20407)
	at android.view.View.draw(View.java:21276)
	at android.view.ViewGroup.drawChild(ViewGroup.java:4417)
	at android.support.v7.widget.RecyclerView.drawChild(RecyclerView.java:4703)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4177)
	at android.view.View.draw(View.java:21550)
	at android.support.v7.widget.RecyclerView.draw(RecyclerView.java:4107)
	at android.view.View.updateDisplayListIfDirty(View.java:20416)
	at android.view.View.draw(View.java:21276)
	at android.view.ViewGroup.drawChild(ViewGroup.java:4417)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4177)
	at android.view.View.updateDisplayListIfDirty(View.java:20407)
	at android.view.View.draw(View.java:21276)
	at android.view.ViewGroup.drawChild(ViewGroup.java:4417)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4177)
	at android.view.View.updateDisplayListIfDirty(View.java:20407)
	at android.view.ThreadedRenderer.updateViewTreeDisplayList(ThreadedRenderer.java:575)
	at android.view.ThreadedRenderer.updateRootDisplayList(ThreadedRenderer.java:581)
	at android.view.ThreadedRenderer.draw(ThreadedRenderer.java:654)
	at android.view.ViewRootImpl.draw(ViewRootImpl.java:3734)
	at android.view.ViewRootImpl.performDraw(ViewRootImpl.java:3529)
	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2866)
	at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1819)
	at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:7781)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1031)
	at android.view.Choreographer.doCallbacks(Choreographer.java:854)
	at android.view.Choreographer.doFrame(Choreographer.java:789)
	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1016)
	at android.os.Handler.handleCallback(Handler.java:883)
	at android.os.Handler.dispatchMessage(Handler.java:100)
	at android.os.Looper.loop(Looper.java:224)
	at android.app.ActivityThread.main(ActivityThread.java:7590)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:539)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:950)

Device{sdkVersion=29, productName='lavender_ru', deviceName='lavender', boardName='sdm660', cpuAbi='armeabi-v7a', manufacturerName='Xiaomi', brandName='xiaomi', modelName='Redmi Note 7'}
 VTL Version: 2.0 DEV, build: 1351b5f

**Comment by gdlbo** [comment]
https://github.com/vtosters/lite/issues/5
