### ISSUE TITLE
Ошибка скачивание всей музыки .mp3

### ISSUE THREAD

**Issue by mrcatgreen** [vtosters/lite#875]
java8.util.concurrent.CompletionException: java.lang.RuntimeException: java.net.SocketException: Software caused connection abort
	at java8.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:305)
	at java8.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:312)
	at java8.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1804)
	at java8.util.concurrent.CompletableFuture$AsyncRun.exec(CompletableFuture.java:1793)
	at java8.util.concurrent.FJTask.doExec(FJTask.java:271)
	at java8.util.concurrent.FJPool.runWorker(FJPool.java:1495)
	at java8.util.concurrent.FJWorkerThread.run(FJWorkerThread.java:122)
Caused by: java.lang.RuntimeException: java.net.SocketException: Software caused connection abort
	at ru.vtosters.lite.music.M3UDownloader.lambda$parse$0(M3UDownloader.java:95)
	at ru.vtosters.lite.music.M3UDownloader$$ExternalSyntheticLambda0.run(Unknown Source:14)
	at java8.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1801)
	... 4 more
Caused by: java.net.SocketException: Software caused connection abort
	at java.net.SocketInputStream.socketRead0(Native Method)
	at java.net.SocketInputStream.socketRead(SocketInputStream.java:118)
	at java.net.SocketInputStream.read(SocketInputStream.java:173)
	at java.net.SocketInputStream.read(SocketInputStream.java:143)
	at com.android.org.conscrypt.ConscryptEngineSocket$SSLInputStream.readFromSocket(ConscryptEngineSocket.java:945)
	at com.android.org.conscrypt.ConscryptEngineSocket$SSLInputStream.processDataFromSocket(ConscryptEngineSocket.java:909)
	at com.android.org.conscrypt.ConscryptEngineSocket$SSLInputStream.readUntilDataAvailable(ConscryptEngineSocket.java:824)
	at com.android.org.conscrypt.ConscryptEngineSocket$SSLInputStream.read(ConscryptEngineSocket.java:797)
	at com.android.okhttp.okio.Okio$2.read(Okio.java:138)
	at com.android.okhttp.okio.AsyncTimeout$2.read(AsyncTimeout.java:213)
	at com.android.okhttp.okio.RealBufferedSource.read(RealBufferedSource.java:51)
	at com.android.okhttp.internal.http.Http1xStream$FixedLengthSource.read(Http1xStream.java:395)
	at com.android.okhttp.okio.RealBufferedSource$1.read(RealBufferedSource.java:372)
	at java.io.InputStream.read(InputStream.java:205)
	at ru.vtosters.lite.utils.IOUtils.readAllBytes(IOUtils.java:75)
	at ru.vtosters.lite.music.M3UDownloader.lambda$parse$0(M3UDownloader.java:87)
	... 6 more

Device information: commit='e47d6ac', sdkVersion=31, productName='sunny_ru', deviceName='sunny', boardName='sunny', manufacturerName='Xiaomi', brandName='Redmi', MiuiUiVersionCode='13', MiuiUiVersionName='V130', MiuiUiVersionIncrementalCode='V13.0.4.0.SKGRUXM', modelName='M2101K7AG'

**Comment by gdlbo** [comment]
а у тебя включен впн?

**Comment by mrcatgreen** [comment]
> а у тебя включен впн?

Нет, не пользуюсь
