### ISSUE TITLE
Ошибка загрузки фотографий в меню выбора

### ISSUE THREAD

**Issue by jade-gt5000** [vtosters/lite#948]
**Опишите сам баг**
При попытке предложить запись и выбрать там альбом "Фото VK" крашиться приложение 

**Опишите действия для воспроизведения ошибки**
1. Открыл паблик и нажал предложить запись
2. Выбрал альбом вышеуказанный

**Опишите ожидаемый результат**
Альбом должен был открыться без проблем

**Скриншот ошибки**
java.lang.VerifyError: Verifier rejected class com.vtosters.lite.general.fragments.PhotosFragment: void com.vtosters.lite.general.fragments.PhotosFragment.onViewCreated(android.view.View, android.os.Bundle) failed to verify: void com.vtosters.lite.general.fragments.PhotosFragment.onViewCreated(android.view.View, android.os.Bundle): [0x46] register v1 has type Undefined but expected Integer (declaration of 'com.vtosters.lite.general.fragments.PhotosFragment' appears in base.apk!classes4.dex)
	at java.lang.Class.newInstance(Native Method)
	at com.vk.core.fragments.FragmentEntry.w1(FragmentEntry.kt:1)
	at com.vk.core.fragments.FragmentNavigationController.a(FragmentNavigationController.kt:68)
	at com.vk.core.fragments.FragmentNavigationController.a(FragmentNavigationController.kt:60)
	at com.vk.core.fragments.FragmentNavigationController$show$1.invoke(FragmentNavigationController.kt:6)
	at com.vk.core.fragments.FragmentNavigationController$show$1.invoke(FragmentNavigationController.kt:1)
	at com.vk.core.fragments.FragmentNavigationController.a(FragmentNavigationController.kt:77)
	at com.vk.core.fragments.FragmentNavigationController.a(FragmentNavigationController.kt:8)
	at com.vk.navigation.NavigationDelegateBottom$h.run(NavigationDelegateBottom.kt:3)
	at com.vk.core.util.ThreadUtils.b(ThreadUtils.kt:5)
	at com.vk.core.util.ThreadUtils.e(ThreadUtils.kt:1)
	at com.vk.navigation.NavigationDelegateBottom.a(NavigationDelegateBottom.kt:80)
	at com.vtosters.lite.FragmentWrapperActivity.onCreate(FragmentWrapperActivity.java:26)
	at android.app.Activity.performCreate(Activity.java:8578)
	at android.app.Activity.performCreate(Activity.java:8557)
	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1384)
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:4147)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:4312)
	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:101)
	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2571)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loopOnce(Looper.java:226)
	at android.os.Looper.loop(Looper.java:313)
	at android.app.ActivityThread.main(ActivityThread.java:8741)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:571)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1067)

Device information: commit='bf1a73f', sdkVersion=33, productName='a53xnaeea', deviceName='a53x', boardName='s5e8825', manufacturerName='samsung', brandName='samsung', OneUiMajorVersion='5', OneUiMinorVersion='0.0', modelName='SM-A536B'

**Информация об устройстве:**
 - Устройство: Samsung Galaxy A53 
 - OS: OneUi 5.0
 - Коммит: bf1a73f

**Дополнительная информация о баге или мыслях почему оно может происходить (если есть)**
У меня много фотографий, очень много, скорее всего ломается при попытке их загрузить, хотя странно, ведь я пытаюсь выложить фотки, которые уже есть на серверах вк.

**Comment by gdlbo** [comment]
https://github.com/vtosters/lite/commit/04f4f7d2ad855e315bdca2f7e4d87f622e9ac3ba
