### ISSUE TITLE
Ошибка в обработке функции getColor()

### ISSUE THREAD

**Issue by evembar** [vtosters/lite#976]
**Опишите сам баг**
После обновлении версии втостерс до 0.5 у меня вылезла ошибка джавы

**Опишите действия для воспроизведения ошибки**
1. Тупо запускал приложение

**Опишите ожидаемый результат**
Интересная лента должна прогружать результаты

**Скриншот ошибки**

**Информация об устройстве:**
 - Устройство: XGody P30
 - OS: Android 5.1 
 - Коммит: fa12e8f (В О Приложении написана версия коммита)

**Дополнительная информация о баге или мыслях почему оно может происходить (если есть)**

Вот что есть в логе
java.lang.NoSuchMethodError: No virtual method getColor(I)I in class Landroid/content/Context; or its super classes (declaration of 'android.content.Context' appears in /system/framework/framework.jar:classes2.dex)
	at ru.vtosters.lite.themes.ThemesHacks.getHackedColor(ThemesHacks.java:44)
	at androidx.core.content.ContextCompat.getColor(ContextCompat.java)
	at com.vk.core.util.ContextExtKt.a(ContextExt.kt:8)
	at com.vk.core.ui.themes.VKThemeHelper.a(VKThemeHelper.kt:67)
	at com.vk.core.ui.themes.VKThemeHelper.a(VKThemeHelper.kt:65)
	at com.vk.core.ui.themes.VKThemeHelper.a(VKThemeHelper.kt:60)
	at com.vk.core.ui.themes.VKThemeHelper.d(VKThemeHelper.kt:2)
	at com.vtosters.lite.MainActivity.onCreate(MainActivity.java:10)
	at android.app.Activity.performCreate(Activity.java:6107)
	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1112)
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2468)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2595)
	at android.app.ActivityThread.access$800(ActivityThread.java:178)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1470)
	at android.os.Handler.dispatchMessage(Handler.java:111)
	at android.os.Looper.loop(Looper.java:194)
	at android.app.ActivityThread.main(ActivityThread.java:5631)
	at java.lang.reflect.Method.invoke(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:372)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:959)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:754)

Device information: commit='52f69c7', sdkVersion=22, productName='P30', deviceName='P30', boardName='P30', manufacturerName='P30', brandName='P30', modelName='P30'

**Comment by gdlbo** [comment]
https://github.com/vtosters/lite/commit/c470062d7005693e8eaff7bf8f24363145b61bcc fixed
