### ISSUE TITLE
Ошибка при нажатие "VT Функции"

### ISSUE THREAD

**Issue by R14ard** [vtosters/lite#992]
У меня выходит ошибка при нажатие (Vt Функции) с уведомлением java.nio.charset.IllegalCharsetNameException: java.nio.charset.CharsetICU[UTF-8]
	at java.nio.charset.Charset.checkCharsetName(Charset.java:201)
	at java.nio.charset.Charset.forName(Charset.java:295)
	at java.net.URLEncoder.encode(URLEncoder.java:57)
	at ru.vtosters.lite.utils.Base64Utils.encodeValue(Base64Utils.java:24)
	at ru.vtosters.lite.utils.SSFSUtils.getSSFSLink(SSFSUtils.java:21)
	at ru.vtosters.lite.ui.fragments.VTSettings.lambda$onCreate$3$ru-vtosters-lite-ui-fragments-VTSettings(VTSettings.java:173)
	at ru.vtosters.lite.ui.fragments.VTSettings$$ExternalSyntheticLambda15.onPreferenceClick(D8$$SyntheticClass)
	at androidx.preference.Preference.performClick(Preference.java:4)
	at androidx.preference.Preference.performClick(Preference.java:1)
	at androidx.preference.Preference$1.onClick(Preference.java:1)
	at android.view.View.performClick(View.java:5698)
	at android.view.View$PerformClick.run(View.java:22565)
	at android.os.Handler.handleCallback(Handler.java:739)
	at android.os.Handler.dispatchMessage(Handler.java:95)
	at android.os.Looper.loop(Looper.java:158)
	at android.app.ActivityThread.main(ActivityThread.java:7230)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1230)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1120)

Device information: commit='8eb7251', sdkVersion=23, productName='j7xeltexx', deviceName='j7xelte', boardName='universal7870', manufacturerName='samsung', brandName='samsung', OneUiMajorVersion='0', OneUiMinorVersion='0.0', modelName='SM-J710F'

**Comment by k1zn** [comment]
исправлено, ждите следующего обновления
